### ISSUE TITLE
--fields should allow nested fields

### ISSUE THREAD

**Issue by llvtt** [mongodb-labs/mongo-connector#255]
Right now, `--fields` only works with top-level fields in a document. It would be nice if `--fields` would be able to handle fields in a sub-document as well.

#### Sub-feature: wildcard characters
so that all fields within a sub-document can be specified more easily in the config file or the command-line. e.g.:

    {
        "subdoc": {
            "a": ...,
            "b": ...,
            "c": ...
        }
        "otherField": 42
    }

we can include all fields within `subdoc` like this:

    mongo-connector --fields 'subdoc.*'

instead of this:

    mongo-connector --fields subdoc.a,subdoc.b,subdoc.c

Allowing wildcard characters only at the end of field names is probably enough for now.

**Comment by gairom** [comment]
Any progress with nested fields support or exclude fields?
Can you please say when it expected to be released?

**Comment by llvtt** [comment]
There hasn't been any significant progress on this feature yet. I'm not
sure when this will be completed.

**Comment by gairom** [comment]
I don't understand why it doesn't work...
My oplog record look like this (both "op" "i" & "u" include the doc):
 "o" : {
                "_id" : ObjectId("xxxxxx"),
                "field1" : "aaaa",
                "field2" : NumberLong("11111"),
                "field3" : "bbbb",
                "field4" : {
                        "sf1" : "ccccc",
                        "sf2" : NumberLong("222222"),
                        "sf3" : "ddddd"
                 }
}

My --fields is "field1","field2","field4.sf1","field4.sf2"
For both inserts and updates I see only field1 & field2...
I don't see in the oplog things like "field4.0"

If I want it to work I need to change my --field to "field4.0","field4.1"??

**Comment by aherlihy** [comment]
https://github.com/mongodb-labs/mongo-connector/commit/4fe5de8d55a6c84d7465bc989f33696144ea9640
