### ISSUE TITLE
strings analyzed even though mapping already has not_analyzed

### ISSUE THREAD

**Issue by sat2050** [mongodb-labs/mongo-connector#270]
things like "Pre paid" is being indexed as "pre" & "paid"

**Comment by llvtt** [comment]
Does the mapping change from its original configuration after running mongo-connector?

**Comment by aherlihy** [comment]
@sat2050 Are you still experiencing this issue? If so, what versions of mongo-connector, doc-manager, mongodb are you using? What is your configuration like?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!
