### ISSUE TITLE
[Feature Request] Allow skipping certain databases.

### ISSUE THREAD

**Issue by minuscorp** [mongodb-labs/mongo-connector#285]
It would be great if somehow you can tell mongo-connector to skip the dumping of certain databases that you don't want to be replicated.

It can be like **mongo-connector --skip databasename1, databasename2**

The changes in the docmanagers aren't too hard I think.

Thank you.

**Comment by llvtt** [comment]
Have you seen the [`namespaces.include`](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#namespacesinclude) option? This allows you to selectively include certain collections. It's not quite the same, but it might work for your needs.

**Comment by minuscorp** [comment]
Yes I saw that feature, that's why I tought It could be interesting to include the database skip option. To skip a whole database and its collections it would be necessary to add database.collection1..collectionN to be skipped, doesn't it?

**Comment by llvtt** [comment]
That is correct. 

To make this feature symmetric with the `namespaces.include` option, this option could be `namespaces.exclude`. If the patterns that each of these options took could include a wildcard (`*`), then it would be easy to include/exclude entire databases instead of just individual collections.

**Comment by minuscorp** [comment]
So it **does** include the wildcard right now? I can use ```exclude mydb.* ``` ?

**Comment by llvtt** [comment]
It does not. I'm just documenting the desired behavior.

**Comment by minuscorp** [comment]
It could be a nice feature, It covers a need that many developers could use.

**Comment by llvtt** [comment]
Most of the discussion around wildcards in namespace include/exclude has moved to #480, so I'm closing this issue as a duplicate.
