### ISSUE TITLE
Understanding migration from one sharded cluster to another

### ISSUE THREAD

**Issue by dharshanr** [mongodb-labs/mongo-connector#289]
Hi,

I am trying to use mongo connector to migrate from one sharded database to another. A few clarifications needed
1. Does the migration process track the oplog from each shard and do a diff migration from each shard?
2. If the target cluster is empty initially will it work or does the user need to go in and manually recreate the whole sharding architecture so that the oplog syncing can work on a shard level?

It will also be good to have this documented in the wiki.

**Comment by llvtt** [comment]
1. `mongo-connector` tails the oplog of each shard separately. I'm not sure what you mean by a "diff migration," though.
2. `mongo-connector` will work if the target is empty. When you provide the "target URL" (`-t`), provide the URL for one or more `mongos`, and the router will take care of routing the documents to the right shards. You'll need to set up sharding on the target yourself manually.

Just to be clear: `mongo-connector` doesn't create a "mirror image" of a sharded cluster. In other words, mongo-connector just listens to one sharded cluster, then does the same operations on the destination mongos router and has no knowledge that the destination is sharded.

**Comment by dharshanr** [comment]
Hi Luke,

Thanks. This helps a lot. How does the mongo-connector have credentials to tail each of the oplog? Also does the connector automatically figure out how many shards are present? In our case the shard credentials (used to connect to mongos) are different from the replica set credentials.

I would like to us a technique similar to the replica set migration you provided earlier in a previous bug. Please let me know if this will work

1. Start the mongo connector with "--nodump" and record the latest oplog entry
2. MongoDump from the source
3. Mongorestore on the destination
4. Configure sharding on the destination
5. Restart the mongo connector

The only question I have now is how to do 1. for each shard.

**Comment by llvtt** [comment]
Mongo Connector uses the same credentials to authenticate to the shards as
to the mongos. I'll open another ticket as a feature request to add the
capability to specify shard credentials separately. The number and URIs of
the shards are determined automatically from the config server.

The strategy you outline seems fine to me, though you might want to
configure sharding before running "mongorestore", so that the restored
documents can be balanced by mongos during the process.

**Comment by aherlihy** [comment]
Hello @dharshanr, has this answered your questions?

I'm going to close this issue due to inactivity but if you still have more questions or are experiencing issues feel free to reopen or file a new issue.

Thank you!
