### ISSUE TITLE
Sync with SOLR doesn't work in large database

### ISSUE THREAD

**Issue by ilfroloff** [mongodb-labs/mongo-connector#298]
Hello! I have a serious problem with syncing solr + mongo. By an empirical way, I have found out that the problem is in mongo-connector.

Requirements:
```
CentOS: 6.2
MongoDB: 3.0.x
SOLR: 5.2.x
mongo-connector: 2.1
```

Briefly, I  have a mongo database (let's call it "db", the collections sum size is ~30GB). Several (six) collections have solr core and each core has mongo-connector. Solr cores and mongo-connectors are synchronized  in real-time.
(mongo-connector option --auto-commit-interval=0). On the host "host1.com" sync works well.

I did a dump of the "db" database  and moved it to "host2.com", where there was another database  - "db1" ("db1" also had a solr-process + mongo-connector for each core (same as "host1.com", that was synchronized in real-time). All worked).
I rolled a dump of "db". Now "host2.com" have 2 bases: "db" and "db1". I run  solr-process + mongo-connector for "db" - it didn't work (but bunch solr + mongo-connector for "db1" still was working). 
I restarted  mongo-connector (of each core) for "db1" - synchronization stopped working, or worked for random cores with large intervals of time ( 10 minutes, and 30 minutes, and an hour, etc).
Restarting of mongo, solr-process and mongo-connector didn't help.

I tried to restart mongo-connector for one of cores in "host1.com" - sync for this core stopped working immediately.

Startup options for mongo:
```
mongod --storageEngine wiredTiger \
       --nojournal \
       --replSet rs0 \
       --dbpath / mongodb / data / \
       --fork \
       --logpath /mongodb/logs/mongod-tiger.log
```

Startup options for SOLR:
```
./solr/bin/solr -s /path/to/cores -p port
```

Startup options mongo-connector (a total of scripts - 6, but all scripts are similar. Difference in collection):
```
mongo-connector -m localhost: 27017 \
                -t http://host1.com:8983/solr/collection1 \
                -d solr_doc_manager \
                -n db.collection1 \
                -g collection1 \
                -o /logs/oplog_collection1.log \
                --logfile /logs/mc_collection1.log \
                --auto-commit-interval = 0
```
Thanks in advance. If you have any questions, please don't hesitate to ask me.

**Comment by llvtt** [comment]
Hey @ilfroloff 

When you say that mongo-connector stopped working, do you mean that it's running but not doing anything, or exiting immediately?

Can you please turn on verbose logging (-v) for mongo-connector and post the logs here (or link to them from your favorite text-paste site)?

Thanks

**Comment by ilfroloff** [comment]
Hi @llvtt 

> When you say that mongo-connector stopped working, do you mean that it's running but not doing anything, or exiting immediately?

It's running but not doing anything. 


> Can you please turn on verbose logging (-v) for mongo-connector and post the logs here (or link to them from your favorite text-paste site)?

You can check logs here (for two different cores):
http://justpaste.it/mo8c (that part repeat any time): core not synchronized with collection
http://justpaste.it/mo8h (that part repeat any time): core synchronized once, but now isn't adding data to SOLR index

Thanks!

**Comment by llvtt** [comment]
>  http://justpaste.it/mo8c (that part repeat any time): core doesn't synchronized with collection

This Exception message sticks out:

    org.apache.solr.common.SolrException: java.io.FileNotFoundException: /srv/dev/cvision-dev/solr/cores/insights/insights/data/tlog/tlog.0000000000000000000 (No such file or directory)

I honestly don't know what this file is, but it might be complaining about a missing directory above it, i.e., /srv/dev/cvision-dev/solr/cores/insights/insights/data/tlog doesn't exist. This could also be a permissions issue.

>  http://justpaste.it/mo8h (that part repeat any time): core synchronized once, but now isn't adding data to SOLR index

These logs show that mongo-connector sent an "add" request to Solr with 1000 documents. It could be that these documents were successfully added, but that the Solr index hasn't been refreshed to make these additions visible. I see that you have `--auto-commit-interval = 0` in the command line, but I think the syntax should be `--auto-commit-interval 0`. It's also a better practice to change the commit interval in solrconfig.xml anyway; see https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr#managing-commit-behavior

**Comment by ilfroloff** [comment]
> I honestly don't know what this file is, but it might be complaining about a missing directory above it, i.e., /srv/dev/cvision-dev/solr/cores/insights/insights/data/tlog doesn't exist. This could also be a permissions issue.

Yes, you are right the problem was in the index folder. Deleting of this folder, restarting and synchronization didn't help me.

> These logs show that mongo-connector sent an "add" request to Solr with 1000 documents. It could be that these documents were successfully added, but that the Solr index hasn't been refreshed to make these additions visible.

May be you know why index wasn't updated?

> I see that you have --auto-commit-interval = 0 in the command line, but I think the syntax should be --auto-commit-interval 0

Sorry, is was just wrongly copied :)
In my run script of mongo-connector, a command line in actually --auto-commit-interval=0 (is the same as --auto-commit-interval 0).

New details: I have tried to create two different mongo-procceses on the same physical server (ports 27017 and 27018 with different folders of data). For each mongo-proccess I have created a database: 
db (an empty database, with all needed collections for solr-cores but without records) - for 27017,
db1 (a dump with capacity 30Gb) - for 27018.

I got the same result as that I have described here https://github.com/10gen-labs/mongo-connector/issues/298#issue-97928915 but after some unsuccessful tries to run mongo-connector for db1 (dump of 30Gb), synchronization started to work (please note, the whole collections was synchronized, index was updated immediately and after restarting of any of mongo-connectors everything continued to work). 
To make synchronization work I added several records into 3 different collections. 

For experiment, I have created totally the same environment (solr + mongo + mongo-connectors) with the separate mongo-proccess (port 27019, different folder), database db2 (initial dump with capacity 30Gb), on this physical server. I have run synchronization for each core - it run just for the biggest collections but while adding data into mongo, solr didn't reindex the changes. Restart of mongo-connector didn't help for mongo port 27018. The most interesting thing is that after restarting mongo-connectors for db1 they stopped to be synchronized in real-time (any changes in collections related to cores, didn't change the index of solr) but started to work in about hour. For db I didn't check (I would have a possibility on monday).

Could you please to answer my several questions:
1) How synchronizaiton solr + mongo works on mongo-connector level. Could you please describe in details the whole process of getting from mongo and adding changes in solr index, or may be you could advice where I can find documentation for mongo-connector and solr_doc_manager.
P.S. If I could see from --verbose logs it's all was caused by oplog that was initially empty for while rolling up the dump.
2) Is there are a full check of the initial state of the solr-core index and related mongo collection? If there is, how could I know the period of time during which this check is performed and the complit synchronization of collections and solr-cores?

**Comment by llvtt** [comment]
1. These pages will provide the best information on the internals of Mongo
Connector:

- https://github.com/10gen-labs/mongo-connector/wiki/System-Overview
- https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr
-
https://github.com/10gen-labs/mongo-connector/wiki/Writing-Your-Own-DocManager

2. There is no check of the initial state of Solr cores. mongo-connector
assumes that the cores are either empty (and no oplog progress file, does
collection dump), or are filled with documents from MongoDB (and continue
replication from the oplog timestamp file).

**Comment by aherlihy** [comment]
@ilfroloff Hello! Did this answer your question?

**Comment by aherlihy** [comment]
Hello! I'm going to close this issue due to inactivity but if the problem persists please feel free to reopen or open a new issue. Thank you!
