### ISSUE TITLE
Support PyMongo 3+

### ISSUE THREAD

**Issue by cjshawMIT** [mongodb-labs/mongo-connector#306]
Hello, trying to use mongo-connector with elastic search and a custom doc manager, but I found out that the current version (2.1) of mongo-connector only supports pymongo < 3.0. My app uses pymongo 3+ -- is it possible to use mongo-connector with the newer versions of pymongo? Some commands are deprecated and eventually will be phased out of pymongo, but for now functionality should be the same?

**Comment by behackett** [comment]
Can you install mongo-connector in a virtualenv?

**Comment by cjshawMIT** [comment]
I do have it in a virtualenv along with my app...

**Comment by llvtt** [comment]
@cjshawMIT Unfortunately, mongo-connector requires PyMongo < 3. There are some breaking changes that PyMongo 3 introduces that mongo-connector hasn't dealt with yet, besides the command deprecations. Once there's a stable version of PyMongo 2.9, which makes the migration to PyMongo 3 easier, I'll make another release of mongo-connector that works with PyMongo >= 2.9. In the meantime, you'll need to use a separate virtualenv for mongo-connector than for your app, if the latter requires the latest version of PyMongo.

**Comment by cjshawMIT** [comment]
@llvtt , thanks for the info and suggestions. Will keep my eye out for future versions of the connector.

**Comment by aherlihy** [comment]
Hello! We released mongo-connector 2.2 today, which requires PyMongo 2.9+.

**Comment by aherlihy** [comment]
I'm going to close the issue, please let me know if you have any more issues. Thank you!
