### ISSUE TITLE
How to handle below scenario in solr or elasticsearch

### ISSUE THREAD

**Issue by gsuresh92** [mongodb-labs/mongo-connector#307]
I am doing daily batch update (around 100K Doc's) in MongoDB and the update process takes about 10 min to complete and if the connector is running during that time.. it is taking too much time to update in Solr or Elasticsearch.. i tried using auto-commit-interval to 1min but it din't help. How does this --auto-commit-interval work ? is it based on document insertion time in MongoDB, Suppose if i am doing bulkInsert in MongoDB, how does the connector handles with --auto-commit-interval=0 option. will it send a request for every doc of bulkInsert ?

**Comment by llvtt** [comment]
The behavior of `--auto-commit-interval` is described in the wiki

- for Elasticsearch: https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-ElasticSearch#managing-refresh-behavior
- for Solr: https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr#managing-commit-behavior.

To summarize: this option has nothing to do with insertion time in MongoDB; it manages how often a "commit" is requested on the remote end.

There's also an entry in the FAQ that gives a few recommendations on how to speed up the connector: https://github.com/10gen-labs/mongo-connector/wiki/FAQ#how-do-i-increase-the-speed-of-mongo-connector

**Comment by gsuresh92** [comment]
@llvtt Thank you very much, it will be helpful if you can share some details about how commits will happen from "remote end" (solr or es) , is it like a request for every "id" or some kind of bulk requests ? and by any chance is that related to "bulkSize" in configuration option ?

2) Regarding my previous question, which one (solr or es)  will be faster in replicating the updates(not inserts) from mongoDB using same configuration options ? 

Thanks

**Comment by llvtt** [comment]
The goal of the "commit" operation makes available any outstanding changes for reading on the remote system. How this happens completely depends on what remote system you're using; I recommend reading the relevant documentation on Solr and Elastic for an explanation of how this works, since these kinds of implementation details are beyond my personal knowledge. Likewise, exactly how fast Solr will be versus Elastic or vice-versa will be very application-dependent. The most useful assessment of this will have to come from your own measurement.

**Comment by trstephen** [comment]
Are there any methods for increasing performance for bulk operations specifically? This is definitely the sort of thing that should go through the _bulk API (for elasticsearch) but it looks like the oplog sees the bulk operation as individual transactions. Even with `--auto-commit-interval=None` the performance hit is severe.

**Comment by aherlihy** [comment]
Hi @trstephen there are no other ways as far as I know. If you would like to make a feature request please open a new ticket.
