### ISSUE TITLE
Custom parameters on kwargs

### ISSUE THREAD

**Issue by hannelita** [mongodb-labs/mongo-connector#312]
Hi,
Would it be possible to pass custom parameters for the constructor, such as the user and password for the destination database (not Mongo)? What would be the proper command line syntax if possible?
For example, I have this
```
mongo-connector -m localhost:27017 -t localhost:9999/mydb -d custom_doc_manager -p mongo_pass -a mongo_adm
```
And I'd like to pass user and password of my custom db.

Thanks in advance!

**Comment by llvtt** [comment]
There isn't a way to do this from the command line, since the syntax might be pretty messy depending on what you want to pass. However, this can be achieved using a configuration file. See https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexargs.

**Comment by aherlihy** [comment]
Hello! I'm going to close this issue, feel free to reopen or file a new one if you are still having problems. Thank you!
