### ISSUE TITLE
Reading from secondary still read from primary

### ISSUE THREAD

**Issue by erickhun** [mongodb-labs/mongo-connector#314]
Hi !

It seems like the mongo connector is reading from the primary , even if we specify that we would like to read on the secondary with a specific tag, and cause some performance issue on the main application.

Here how looks like the connection string
````
mongodb://MONGOS_SECONDARY_STRING:10000/?readPreference=secondary&readPreferenceTags=use:backup
````

I noticed also in the progress file and the debug the mention of the secondary and the primary 
````
MongoConnector: Starting connection thread MongoClient([u'SECONDARY:10004', u'PRIMARY:10004'])
````

Is it a normal behavior? I was wondering if I missed anything to make sure that it only connect to secondary?

Thank you

**Comment by howardkhl** [comment]
Where are you currently running Mongo Connector process, on primary, secondary, or a separate server?

**Comment by erickhun** [comment]
@howardkhl it's running on a separate server.

**Comment by Sebmaster** [comment]
@erickhun See #321 if you haven't seen it already.

**Comment by aherlihy** [comment]
@erickhun Hi, are you still experiencing this issue?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!
