### ISSUE TITLE
mongo-connector fails to start after being stopped

### ISSUE THREAD

**Issue by XDestination** [mongodb-labs/mongo-connector#317]
When I stop the mongo-connector and then start it again afterwards it first looks like it is continuing where it stopped, but after a couple of seconds it stops without an actual error message and just prints "Mongo DocManager Stopped: If you will not target this system  again with mongo-connector then you may drop the database __mongo_connector, which holds metadata for Mongo Connector.".

Because of that I have to resync mongo-connector everytime it gets stopped or if it fails for any reason.

**Comment by llvtt** [comment]
What are the contents of the log file? Is anything else printed to
stdout/stderr?

**Comment by XDestination** [comment]
I don't see any other message in the logs, even though I set the verbosity to 3.

**Comment by XDestination** [comment]
I've tried it now again with a verbosity level of 2 and now it is running for over an hour. Maybe this solved it.
