### ISSUE TITLE
On initial import mongo-connector misses documents

### ISSUE THREAD

**Issue by XDestination** [mongodb-labs/mongo-connector#318]
When I do a resync of the data, mongo-connector starts with the initial import of the data, but after the initial import there are in fact a lot of documents missing and mongo-connector is not outputting any error message. After that it continues with the replication on the incomplete dataset.
In case it matters: I'm trying to sync four collections:
* coll A ~ 15Mio docs (~80GB datasize)
* coll B ~ 5Mio docs (~62GB datasize)
* coll C ~6Mio docs (~15GB datasize)
* coll D ~ 30k docs (~80MB datasize)

All collections are sharded over 7 shards and synced onto a single instance of mongoDB.

**Comment by llvtt** [comment]
When data is continuously being written to the source cluster,
mongo-connector will dump only what it currently sees from relevant
collections to the destination. This *might* include some of the data
currently being written to the source while this is going on. After the
initial dump is complete, mongo-connector will begin to tail the oplog to
pick up the rest of the inserts.

Is it possible that some of the "documents missing" might be documents that
are just being written while mongo-connector is performing its initial
dump? Then these documents will eventually make it to the destination when
the corresponding insert ops are picked up in the oplog.

**Comment by XDestination** [comment]
What confuses me is the following:
The dump seems to have finished (at least there are now entries in the oplog.timestamp file), but only coll A seems to be finished (When comparing against the source collection only a couple of documents are missing and those seem to get inserted by the replication process - I even checked: coll A already contains documents that were added hours after the start of the initial dump) and the other 3 collections are not yet close to being fully replicated (f.e. coll B is still missing 3/4 of the documents and of course those documents were already in the source collections before the dump started).

**Comment by XDestination** [comment]
The initial import ran for over three days now, but it looks like the data is consistent now with the source. I still don't understand why one collections is already updated through the replication, while others still seem to be in the initial-import stage, but at least it seems to work :)
