### ISSUE TITLE
How is mongo-connector handling chunk-migrations and the deletions...

### ISSUE THREAD

**Issue by XDestination** [mongodb-labs/mongo-connector#319]
...caused by the rangeDeleter after migrations?

For me it looks like there could be the following race condition:
* chunk is moved from shard A to shard B -> mongo-connector reads inserts (or upserts) from the oplog of shard B for the documents in the chunk and applies them
* rangeDeleter deletes documents of the chunk on shard A -> mongo-connector reads the deletes for the documents from the oplog of shard A and applies them

Result the documents in the chunk that got moved are being deleted.

Can this happen, or am I on a complete wrong track?
If it can happen is there any solution to this problem (I can't really think of one :|)?

**Comment by llvtt** [comment]
Any oplog documents that have `"fromMigrate": True` set are ignored:
https://github.com/10gen-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L194-L196

**Comment by XDestination** [comment]
Thanks for the clarification.
