### ISSUE TITLE
[Question] ElasticSearch suggester

### ISSUE THREAD

**Issue by speciose** [mongodb-labs/mongo-connector#327]
To implement ElasticSearch autocomplete I need to copy some field to "suggest" field.
For example I have { name: "Arnold"} and I need to put inside mongo { name: "Arnold", suggest: { input: "Arnold"} }
Can I somehow make this "suggest" field using mongo-connector?

**Comment by llvtt** [comment]
There isn't any feature like that in mongo-connector right now. The
documents sent to Elasticsearch look essentially the same as they do in
MongoDB, so you'll either need to change the documents mongo-side or modify
elastic_doc_manager.py to suit your needs.

**Comment by qlqllu** [comment]
@llvtt is this feature in the latest release(2.5.1)? If not, do you have plan to add this feature?
And, what do you mean by `change the documents mongo-side`?

Please forgive me that I know little about both mongo-connector and elaticsearch.

**Comment by ShaneHarvey** [comment]
There is no feature to accomplish this in 2.5.1. "`change the documents mongo-side`" means to update all the `{ name: "Arnold"}` documents in MongoDB to `{ name: "Arnold", suggest: { input: "Arnold"} }` and mongo-connector will sync the updated documents.

It might also be possible to do thi  with an Elasticsearch ingest node processor that automatically adds the `suggest : { input: "<name>"}` field. I think this could be done with a Painless script, see https://www.elastic.co/guide/en/elasticsearch/reference/5.3/script-processor.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.3/modules-scripting-painless.html

Something like this may work:
```js
{
  "script": {
    "lang": "painless",
    "inline": "ctx.suggest = ['input': ctx.name]"
  }
}
```
