### ISSUE TITLE
Restart mongo-connector instance

### ISSUE THREAD

**Issue by Perchework** [mongodb-labs/mongo-connector#328]
Hi,

When I restart an instance of mongo connector, he don't restart at the last oplog ts, but he check all the documents (I think), because the connector take a lot of time before restarting to syncronize data.

I use the elastic doc manager, my oplog.timestamp file look fine:

```
[["Collection(Database(MongoClient(['prod-2.mongo.service.consul:27017', 'prod-3.mongo.service.consul:27017', 'prod-1.mongo.service.consul:27017']), 'local'), 'oplog.rs')", 6200037230262616072], ["Collection(Database(MongoClient(['prod-1.mongo.service.consul:27017', 'prod-3.mongo.service.consul:27017', 'prod-2.mongo.service.consul:27017']), 'local'), 'oplog.rs')", 6200197836269682689], ["Collection(Database(MongoClient(['prod-1.mongo.service.consul:27017', 'prod-2.mongo.service.consul:27017', 'prod-3.mongo.service.consul:27017']), 'local'), 'oplog.rs')", 6198830722409562113]]
```

I tried to restart with or without --no-dump option, same results.

For exemple, I've got a collection with 2.5 millions of docs, the initial dump take around 1h30min, and when i restart the connector, the syncronize restart after 1h30min...

Realy sorry for my bad english, and thanks for yout reply.

Thomas.

**Comment by llvtt** [comment]
Can you please provide debug-level logs for mongo-connector when you try to
start it using your timestamp file?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more problems. Thanks!
