### ISSUE TITLE
Issue connecting to solr and mongo running in cloud

### ISSUE THREAD

**Issue by abhijeetd1** [mongodb-labs/mongo-connector#330]
I was able to successfully use this index data from mongodb to solr in my local installation.. however when using the same with a solr instance running on cloud (opensolr).. I am getting following error when starting the mongoconnector..

c:\python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not a
  InsecurePlatformWarning
Logging to mongo-connector.log.

should I follow any additional steps to make it work  .looking for some input around this..

**Comment by behackett** [comment]
This isn't a bug in mongo-connector. It appears to be a warning raised from urllib3, which is packaged by the requests library. I suggest asking the requests project:

https://github.com/kennethreitz/requests

**Comment by behackett** [comment]
Actually, this warning, with workarounds, is documented for urllib3 here:

https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
