### ISSUE TITLE
when use elasticsearch shield,   how to make mongo-connector  auth the basic auth?

### ISSUE THREAD

**Issue by iamliqiang** [mongodb-labs/mongo-connector#331]
i use elasticsearch shield,and set basic http auth
how to make mongo-connector authed with basic http auth?

**Comment by iamliqiang** [comment]
the problem was solved,  you can set the basic http auth throught "docManager"  targetURL options

![image](https://cloud.githubusercontent.com/assets/1259331/10267096/36129c58-6ab7-11e5-9e03-d31fac0c1b5f.png)

**Comment by aherlihy** [comment]
Ok, I'm going to close the issue. Thank you!
