### ISSUE TITLE
Specifying namespaces via config file

### ISSUE THREAD

**Issue by hannelita** [mongodb-labs/mongo-connector#332]
Hi,
I tried to specify the namespaces to be included via config file such as [this example](https://github.com/mongodb-labs/mongo-connector/blob/master/config.json) suggests, but it seems that this options is being ignored and all the collections were imported. However, specifying via *-n* worked pretty well.

My config.json:
```
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "localhost:27017",
    "oplogFile": "oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 1,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "mongo-connector.log",
        "__format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,

        "__type": "syslog",
        "__host": "localhost:512"
    },

    "namespaces": {
      "__include": ["test.talks"],
      "mapping": {"test.talks": "test.talks"},
      "gridfs": []
    },

    "docManagers": [
        {
            "docManager": "neo4j_doc_manager",
            "targetURL": "http://localhost:7474/db/data",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null,
            "args": { 
              "clientOptions": {
                "collection": "talks"
              }
            }
        }
    ]
}
```
(I tried several variations for "namespaces":
```
"namespaces": {
      "__include": ["test.talks"],
      "mapping": {"test.talks": "test.talks"}
    },
```
or
```
"namespaces": {
      "__include": ["test.talks"]
    },
```
But no success.

Just a quick try, maybe it's because this helper is always being initialised with the defaults?
https://github.com/mongodb-labs/mongo-connector/blob/db88747c4a89560490e2ebb8c85d00f00724ad8d/mongo_connector/connector.py#L106

Thanks in advance!

**Comment by llvtt** [comment]
As the configuration file notes at the top, configuration options prefixed
with "__" (two underscores) are ignored. This is used as a "comment
syntax." Just remove the two leading underscores in "include" and this
should work.

**Comment by hannelita** [comment]
@llovett Oh I'm sorry about this. I hadn't noticed. Thank you so much for the information.

Checking the [Configuration File Wiki page](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-File), I noticed that maybe we could improve it. What do you think of something quickly descriptive such as:

=========================================
You can use a custom configuration file to specify some options to mongo-connector.

Refer to [this example](https://github.com/mongodb-labs/mongo-connector/blob/master/config.json) to see how the file is structured. Please check [this page](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options) to a full explanation of the possible options that you can set. Taking a look at the [tests](https://github.com/mongodb-labs/mongo-connector/blob/master/tests/test_config.py) also might be helpful to understand what and how you can configure it.

Please note that any option that starts with *__* will be ignored. For example, 

```
"namespaces": {
  "__include": ["test.talks"]
},
```

Will have the *__include* option ignored.

To invoke _mongo-connector_ with a confuration file option, run:

```
mongo-connector -c config.json
``` 
=========================================

(I'm sorry for making suggestions here; is there a way to submit these doc improvements as a PR?)
Thanks once again.

**Comment by llvtt** [comment]
I added a bit more information to the top of the [configuration options](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options) page. What do you think? Also, I believe the wiki is free to edit.

**Comment by hannelita** [comment]
@llovett Thanks you so much. I added extra info there. Hope it looks fine to you.
