### ISSUE TITLE
how to connect with amazon ES service

### ISSUE THREAD

**Issue by yodaiken** [mongodb-labs/mongo-connector#337]
Hi—

I'm trying to use mongo-connector with Amazon's new hosted Elasticsearch (http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html).

I believe that it's not using normal Elasticsearch Shield etc, but rather is using Amazon's rather complex authentication scheme.

Any tips for getting mongo-connector to work?

Best,
Aaron

**Comment by llvtt** [comment]
There are two ways of passing arguments to the internal Elasticsearch client:

1. Pass options encoded in the url (`-t` option)
2. Pass options in the [configuration file](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexargs). Using `clientOptions` in this dictionary allows you to pass in individual options. For example, `"args": {"clientOptions": {"foo": XXX}}` sets `foo=XXX` in the constructor for the [Elasticsearch client](http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch).

**Comment by yodaiken** [comment]
I think the issue is that you need a lot of special headers (which change throughout the session?) to use Amazon's authentication service -- ideally there would be some way to get Elasticsearch to connect via Amazon's SDK.

**Comment by consulthys** [comment]
As commented [here](http://stackoverflow.com/a/33459628/4604579), the only real option is to allow the `es_doc_manager` to talk to an IAM-secured Amazon Elasticsearch cluster and the only way to go is that the embedded Elasticsearch Python client be [empowered to do so](https://github.com/elastic/elasticsearch-py/issues/280) by means of some additional configuration option or simply with another doc manager dedicated to the Amazon Elasticsearch service.

**Comment by llvtt** [comment]
You can pass arbitrary arguments to the Elasticsearch client's constructor
with the following option:
https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-ElasticSearch#customizing-behavior-of-the-elastic-client

You should be able to accomplish what was described on elasticsearch-py's
Github page with that option using the mongo-connector configuration file.

On Sat, Oct 31, 2015 at 11:07 PM, Valentin Crettaz <notifications@github.com

**Comment by yodaiken** [comment]
Hi @llvtt -- as far as I can tell, mongo-connector only allows passing arbitrary primitives as arguments. As you can see in @consulthys' link (https://github.com/elastic/elasticsearch-py/issues/280#issuecomment-147527301) to support AWS we need to a) import a new package and b) pass elasticsearch a reference to an instance of a class from that package.

Am I missing something?

**Comment by llvtt** [comment]
@yodaiken You're totally right; this doesn't look currently possible with mongo-connector. This could be included in a future Elastic DocManager if there's enough interest in having this, but right now I'd like to keep mongo-connector itself as lean as possible and encourage others to write their own DocManagers as plugins, rather than adding the kitchen sink to the project.

Adding and setting up `requests_aws4auth` looks relatively straightforward, though. I'd recommend creating an `AWS4Auth` instance and grabbing the required parameters out of environment variables. Then, modify the call to the constructor of `Elasticsearch` to take in the AWS4Auth object in the `http_auth` parameter, following the code snippet that @consulthys linked to.

Let me know if you need any further help working on this.

**Comment by sbrunov** [comment]
Hello, @llvtt!

> I'd like to keep mongo-connector itself as lean as possible and encourage others to write their own DocManagers as plugins, rather than adding the kitchen sink to the project.

This sounds reasonable. Please consider extracting the existing «built-in» document managers from the Mongo Connector as separate plugins. A plugin — an extension of a system, not «a system itself».

Best regards,
Sergey Brunov.

**Comment by aherlihy** [comment]
I'm closing this for now, but feel free to file a new issue or re-open if you like. We're currently working on pulling out the Elastic doc manager into a separate package (to handle supporting both 1.x and 2.x) so it may be easier to extend the elastic search doc managers in the future. Thank you!
