### ISSUE TITLE
Extending existing DocManager

### ISSUE THREAD

**Issue by yashgt** [mongodb-labs/mongo-connector#338]
The steps for creating your own DocManager at https://github.com/mongodb-labs/mongo-connector/wiki/Writing-Your-Own-DocManager shows the class being derived from DocManagerBase.
 
What do I need to do to derive from an existing DocManager like SolrDocManager? I want to retain most of the functionality of SolrDocManager and change only part of it.

**Comment by llvtt** [comment]
You can do:

from mongo_connector.doc_managers.solr_doc_manager import DocManager as SDM

class MyDocManager(SDM):

    # continue as on the wiki page. non-overridden methods will come from
Solr's DocManager

**Comment by aherlihy** [comment]
@yashgt has this addressed your issue?

**Comment by yashgt** [comment]
Yes. Thanks.
