### ISSUE TITLE
NoDump to true is not working

### ISSUE THREAD

**Issue by bappr** [mongodb-labs/mongo-connector#344]
Hi,

I am using the mongo-connector to index data from mongo to elasticsearch.
I specified the value of the field noDump to true because I just want the mongo-connector to read the oplog from the last operation.

But it is not working.
The mongo-connector is dumping my collection and so, it does not care about the field noDump.

Benjamin

**Comment by johnd08** [comment]
Just came across the exact same thing, mongo-connector version 2.1.

**Comment by aherlihy** [comment]
Hello!

Sorry for the delay in getting back to you. Can you please tell me the version of Mongo-Connector, MongoDB, and Elastic that you are using as well as how you are running Mongo-Connector?

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more issues. Thanks!

**Comment by rodriguezsergio** [comment]
I'm experiencing this as well. At first, I thought it wasn't working at all because I was seeing zero results being returned in Kibana, but now I see that it's backfilling ES with old data.

Running the following:
mongo-connector (2.4.1)
mongodb 3.2.3
ElasticSearch 2.4.0
