### ISSUE TITLE
Update fix not present with pip install

### ISSUE THREAD

**Issue by jdenison** [mongodb-labs/mongo-connector#352]
Hi, 
I have a Ubuntu VM, set up with Vagrant and Ansible scripts, that provides a Solr instance and a MongoDB server. The ansible scripts install mongo-connector with pip. Recently, I've faced a problem when updating documents, and I found that the fix exists since that commit : https://github.com/mongodb-labs/mongo-connector/commit/107a0e24e5c6415effcf6b880e81d2cf19bba7c2

Unfortunately, it seems that the version of Mongo-connector installed by pip does not have that fix. 

Do I need to install Mongo-connector manually to have the very last version?

Thanks.

**Comment by aherlihy** [comment]
Hello @jdenison, the most recent version (2.3.x) should be up on PyPI now. If you still have issues installing feel free to file a new issue or reopen this one. Thanks!
