### ISSUE TITLE
mongo-connector not pulling data to solr after the addition of copyField 

### ISSUE THREAD

**Issue by Wendy8787** [mongodb-labs/mongo-connector#354]
Hi,

I use mongo-connector, mobgodb v3, solr 5.3 for full text search. It works but I would boost ranking on some fields. I have over 20 fields to search against, only want to boost ranking on title, keywords, teaser. So I went to create a copyField to host the values from these fields w/o ranking boost. 

After I made change in the schema file of managed-schema, I can restart solr, restart  mongo-connector, but no data were under /data/index.

What could be the cause of the issue? Any suggestions?  Thanks! --Wendy

1. coomad line that I used:
./mongo-connector -m localhost:27017 -t http://localhost:8983/solr/keywords -n pdb101v2.motm_articles --auto-commit-interval=0 -d solr_doc_manager

2.  part of the schema file:
```xml
<field name="keywords.0" type="string" indexed="true" stored="true"/>
<field name="keywords.1" type="string" indexed="true" stored="true"/>
<field name="keywords.2" type="string" indexed="true" stored="true"/>
<field name="keywords.3" type="string" indexed="true" stored="true"/>
<field name="keywords.4" type="string" indexed="true" stored="true"/>
<field name="keywords.5" type="string" indexed="true" stored="true"/>
<field name="keywords.6" type="string" indexed="true" stored="true"/>
<field name="keywords.7" type="string" indexed="true" stored="true"/>
<field name="keywords.8" type="string" indexed="true" stored="true"/>
<field name="keywords.9" type="string" indexed="true" stored="true"/>
<field name="keywords.10" type="string" indexed="true" stored="true"/>
<field name="keywords.11" type="string" indexed="true" stored="true"/>
<field name="keywords.12" type="string" indexed="true" stored="true"/>
<field name="keywords.13" type="string" indexed="true" stored="true"/>
<field name="keywords.14" type="string" indexed="true" stored="true"/>
<field name="keywords.15" type="string" indexed="true" stored="true"/>
<field name="klist" type="string"  indexed="true" stored="true" multiValued="true"/>

 <copyField source="keywords.0" dest="klist"/>
  <copyField source="keywords.1" dest="klist"/>
  <copyField source="keywords.2" dest="klist"/>
  <copyField source="keywords.3" dest="klist"/>
  <copyField source="keywords.4" dest="klist"/>
  <copyField source="keywords.5" dest="klist"/>
  <copyField source="keywords.6" dest="klist"/>
  <copyField source="keywords.7" dest="klist"/>
  <copyField source="keywords.8" dest="klist"/>
  <copyField source="keywords.9" dest="klist"/>
  <copyField source="keywords.10" dest="klist"/>
  <copyField source="keywords.11" dest="klist"/>
  <copyField source="keywords.12" dest="klist"/>
  <copyField source="keywords.13" dest="klist"/>
  <copyField source="keywords.14" dest="klist"/>
  <copyField source="keywords.15" dest="klist"/>
 <dynamicField name="*klist" type="string"   indexed="true"  stored="true" multiValued="true"/>
```

**Comment by llvtt** [comment]
mongo-connector won't re-index any documents if it thinks they were replicated already. Try using another oplog.timestamp file, or delete the existing one.

**Comment by Wendy8787** [comment]
Hi IIvtt,

I did delete the existing oplog.timestamp file and the mongo-connector.log file. 
No data were pulled over under Solr folder of  /solr/server/core/data/index/

I used the following to start mongo-connector.  Do you know if mongo-connector/solr_doc_manager/copyFields have been tested and will work?  Thanks for your help!
 
./mongo-connector -m localhost:27017 -t http://localhost:8983/solr/keywords -n pdb101v2.motm_articles --auto-commit-interval=0 -d solr_doc_manager

**Comment by llvtt** [comment]
Can you provide the logs from mongo-connector?

**Comment by Wendy8787** [comment]
Hi llvtt,

Thank you very much for your response.  The log file has no data (see below). 

 -rw-r--r-- 1 wtao rcsbdev       0 Nov 17 14:49 mongo-connector.log
-rw-r--r-- 1 wtao rcsbdev     101 Nov 17 15:07 oplog.timestamp

 I did some changes, now the mongo-connector pulls data from mongodb to ./solr/server/keywords/data/index/
 But I don't see the copyField (see the attached file below). Do I suppose to see the copyField data here?  Thank you very much for your help!

[motm-index-data.txt](https://github.com/mongodb-labs/mongo-connector/files/37149/motm-index-data.txt)

**Comment by Wendy8787** [comment]
Hi llvtt,

Thank you so much! You are right, I see it :-)
You can close this ticket now. 
Now I need to debug on solr end.

All the best!

Wendy
