### ISSUE TITLE
Use single collection for __mongo_connector

### ISSUE THREAD

**Issue by aganapat** [mongodb-labs/mongo-connector#355]
I noticed that the existing mongo doc manager creates a collection for every namespace found in the source. This doesnt scale well in our scenario where there are lots of databases and collections. Also these collections dont seem to trim the data. 

I am writing up a custom doc manager that makes a single collection for recording all the namespace activity in __mongo_connector database and capping it by the same size as the oplog. Please let me know if you see any issues with this.

**Comment by llvtt** [comment]
That sounds like a fine idea to me. If the changes are only these two things (restricting __mongo_connector to a single collection and making it capped to the size of the oplog), then feel free to make a pull request and I'll merge it. These changes sound generally helpful.

**Comment by aganapat** [comment]
@llvtt thanks, in that case, I will make it an option in the base mongo_doc_manager and send you a pull request.

**Comment by aganapat** [comment]
@llvtt I have created a PR, the tests pass now except for test_elastic_doc_manager (this seems like a failure on master as well). Please take a look and provide your comments.

**Comment by llvtt** [comment]
Thanks for the hard work! I'll looking into what's going on in the Travis
build and then make some comments on these changes.

**Comment by aherlihy** [comment]
Closed because PR was merged.
