### ISSUE TITLE
incompatible PyMongo requirements between mongo-connector and mongo-orchestration

### ISSUE THREAD

**Issue by oxymor0n** [mongodb-labs/mongo-connector#360]
I'm working on a fork of your mongo-connector repo, and when running test I'm running into this issue. mongo-connector requires PyMongo >= 2.7.2, < 3.0.0, while mongo-orchestration requires PyMongo >= 3.0.2. 

Any advice on what version I should install?

**Comment by behackett** [comment]
We're currently updating mongo-connector to require PyMongo 2.9+. That should resolve this issue.

**Comment by aherlihy** [comment]
Hello! We released mongo-connector 2.2 today which requires PyMongo 2.9+. Hopefully this will get rid of the issue entirely.

**Comment by oxymor0n** [comment]
thanks!
