### ISSUE TITLE
configure index with type for elasticsearch

### ISSUE THREAD

**Issue by chandra9990** [mongodb-labs/mongo-connector#362]
Hi,

I have a problem with mongo connector. i need to define index for elastic search with collection name, but index name is always table name. How can i do it ?

Thanks in advance

**Comment by aherlihy** [comment]
Hello! Unfortunately the way data is mapped from mongodb to elastic is the collection corresponds to a type, and the database corresponds to an index. You can modify the names of the index with the (namespace mapping)[https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#namespacesmapping] argument, but collection is always the type name. There isn't any way to achieve what they want directly with mongo-connector. 

However, if the collection you're interested in exists in its own MongoDB database, it will have its own index in Elastic, and you can rename that collection to whatever you want and get a similar effect.
