### ISSUE TITLE
Oplog-Manager: Incorrect nested fields insert/update behaviour

### ISSUE THREAD

**Issue by robertaistleitner** [mongodb-labs/mongo-connector#372]
I'm not sure if someone else had this issue before (I didn't find anything in the issues), so I just made a fix for it. The description of the commit describes the problem as well as the solution to it:
robertaistleitner/mongo-connector@5168f6e8f8d464d48deb4557d4b848ce90792181

Your feedback is very much appreciated :wink:

**Comment by llvtt** [comment]
It's been awhile since I've looked at the issues related to projecting fields in mongo-connector. I recall something tricky about handling updates, but it looks like this patch deals with `$set`/`$unset` cases. Would you mind making this into a pull request?

**Comment by robertaistleitner** [comment]
I created a pull request for my fix.. You can find it here: #382

**Comment by aherlihy** [comment]
Hello!

Since this issue has been addressed by [this commit](https://github.com/mongodb-labs/mongo-connector/commit/4fe5de8d55a6c84d7465bc989f33696144ea9640), I'm going to close this issue. Thank you for identifying the bug and helping us come up with a solution!
