### ISSUE TITLE
Mongo-Connector over ElasticSearch

### ISSUE THREAD

**Issue by pakkk** [mongodb-labs/mongo-connector#375]
Hello!

I am working on:
- MongoDB version 3.0.3.
- Elastic Search 2.1.1
- Kibana 4.3.1
- Attachment plugin

I followed all your steps (from your Wiki page about GridFs) to launch mongo-connector and create the mapping, but I cannot see any information about the mongodb documents in the Kibana view:

1) mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager
2) curl -XPUT http://localhost:9200/myindex
3) curl -XPUT http://localhost:9200/myindex/fs.chunks/_mapping -d "{\"fs.chunks\": { \"properties\": { \"data\": {\"type\": \"attachment\"}}}}"
4) The result of the previous point: {"acknowledged":true}

My collection name is "fs.chunks"
My field name is "data"

Do I need to do anything else to see it in the Kibana view? Anything wrong?

On the other hand, if I want to index other normal fields (how could I do it?)

Many thanks!

Regards,
Paco.

**Comment by behackett** [comment]
Hi. mongo-connector does not yet support Elasticsearch 2.x. See #351. We will be adding support soon.

**Comment by pakkk** [comment]
Many thanks Bernie,

What ElasticSearch, Marvel, Kibana versions do you recommend to works with Mongo-Connector and GridFs?

On the other hand, any documentation to learn how to get normal fields from MongoDB via mongo-connector to ElasticSearch?

Many thanks,

Regards,
Paco.

**Comment by behackett** [comment]
I'm not familiar with Marvel and Kibana. You can use any up to date 1.x version of Elaticsearch. The documentation for use with ES (including some information about GridFS) is available here:

https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch

**Comment by pakkk** [comment]
Thank you :)

**Comment by marcinkubica** [comment]
i think you confused elastic mapping with mongo-connector mapping.

Check mapping closely in yml file.

For the starters you don need to create mapping on elastic side - it will
do it for you. Later on you might want to adjust as you see fit.

You still need to create index patter in kibana, also you need at least one
record to have date-time properly indexed ( not as string )

Btw. Im using dev2.0 version of mongo-connector ( with caution and hacks in
few places ) with ES2.1.1 and generally it works ok. Waiting eagerly for
proper release though ;)





-- 
Sent from Gmail Mobile

**Comment by pakkk** [comment]
Many thanks for your reply Marcin,

Yes, I just configure mongo-connector and the elasticsearch version 1.7.4, and I can see the mongo documents via Marvel ;)

On the other hand, why the attachment is in base64? Could I change any configuration from mongo-connector to have my content as initially (XML)? Or do you know the way to search via elasticsearch over Base64 strings?

Many thanks!

Regards,
Paco.
