### ISSUE TITLE
how to index data in array?

### ISSUE THREAD

**Issue by Wendy8787** [mongodb-labs/mongo-connector#377]
Hi,

Is it possible to index the data in an array with a wid-card and combine the following statement to two lines?

Currently, I use the following way to index each items in sections array and it works. But it's length and also could miss out data if the array list continue to increase.  Thanks!
----------------------------------------------------------------------------------------------------------------------
<field name="sections.0.parts.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.parts.0.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.0.parts.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.parts.1.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.0.parts.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.parts.2.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.0.parts.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.parts.3.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.0.parts.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.parts.4.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.parts.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.parts.0.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.parts.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.parts.1.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.parts.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.parts.2.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.parts.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.parts.3.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.parts.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.parts.4.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.2.parts.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.parts.0.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.2.parts.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.parts.1.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.2.parts.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.parts.2.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.parts.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.parts.3.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.parts.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.parts.0.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.parts.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.parts.1.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.parts.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.parts.2.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.parts.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.parts.3.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.parts.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.parts.4.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.4.parts.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.4.parts.0.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.4.parts.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.4.parts.1.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.4.parts.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.4.parts.2.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.4.parts.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.4.parts.3.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.4.parts.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.4.parts.4.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="plist_stem" type="pdb_text_stem"  indexed="true" stored="true" multiValued="true"/>
<copyField source="sections.*" dest="plist_stem"/>

**Comment by Wendy8787** [comment]
[motm_195_short_sample_v2.txt](https://github.com/mongodb-labs/mongo-connector/files/96577/motm_195_short_sample_v2.txt)

**Comment by Wendy8787** [comment]
<field name="sections.0.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.0.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.1.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.2.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.3.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.4.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.5.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.0.5.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.1.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.0.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.1.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.2.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.3.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.4.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.5.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.1.5.content" type="pdb_text_stem" indexed="true" stored="true"/>


<field name="sections.2.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.0.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.1.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.2.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.3.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.4.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.5.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.2.5.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="sections.3.0.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.0.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.1.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.1.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.2.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.2.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.3.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.3.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.4.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.4.content" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.5.heading" type="pdb_text_stem" indexed="true" stored="true"/>
<field name="sections.3.5.content" type="pdb_text_stem" indexed="true" stored="true"/>

<field name="plist_stem" type="pdb_text_stem"  indexed="true" stored="true" multiValued="true"/>
<copyField source="sections.*" dest="plist_stem"/>

**Comment by behackett** [comment]
Hi. Are you posting images as your comments? I see no content for most of your issue description and all of you last comment. Can you please describe your problem in plain text?

**Comment by Wendy8787** [comment]
Hi behackett,

Thank you for getting back to me. See the attached file for part of the managed-schema. 
My question is there a way to define these fields just using two lines dynamically, instead of spelling them out like I did in the attached file.
Sorry for the empty spaces. For some reasons the web interface didn't take the content when I submitted previously.
[managed-schema.txt](https://github.com/mongodb-labs/mongo-connector/files/97975/managed-schema.txt)

**Comment by llvtt** [comment]
Dynamic fields can only have wildcard characters at the start and the end: https://wiki.apache.org/solr/SchemaXml

If you know that there are a certain number of items in your array, your approach is fine, even if it is lengthy. Otherwise, you can change the schema of your documents to be friendlier for Solr search.

**Comment by Wendy8787** [comment]
Hi llvtt,

Thank you for getting back to me!  The number of items in my array is no limit. 
1. Is it possible to use Dynamic Array with a wild card?
2. To change the schema of the documents to be friendlier for Solr search: I suggested to store the entire article body as one element, but didn't go too far.  Any other suggestions?

Thank you!

**Comment by llvtt** [comment]
Perhaps you can create a `copyField` with a source of `*.heading` and copy it to some `multiValue` field. I suggest a full read of the [schema xml](https://wiki.apache.org/solr/SchemaXml) documentation on the Solr wiki to see what Solr's capabilities are for handling this sort of situation.

**Comment by Wendy8787** [comment]
Hi llvtt,

OK, thank you for your help!
