### ISSUE TITLE
where is default config.json file when instal use pip?

### ISSUE THREAD

**Issue by jackbbhua** [mongodb-labs/mongo-connector#380]
hi,i install by <code> pip install mongo-connector command </code> .but can not find config.json any where.and i can not find the folder to Installing as a Linux Service use <code> python setup.py install_service </code> command.can you find out for me?thank you.

**Comment by behackett** [comment]
https://github.com/mongodb-labs/mongo-connector/wiki/Installation#installing-as-a-linux-service

According to the docs config.json should be in /etc
