### ISSUE TITLE
How to enrich document before indexing in ES for example?

### ISSUE THREAD

**Issue by nvartolomei** [mongodb-labs/mongo-connector#384]
Hello,

I have a collection with documents that keep an ObjectId reference to documents in another collection. Before sending document to index I need to retrieve the referenced document and to merge them (denormalize).

Can someone link an example?

**Comment by marcinkubica** [comment]
Hi, I would try discuss.elastic.co logstash section.

**Comment by gustavodegeus** [comment]
+1

**Comment by aherlihy** [comment]
Hello! I'm going to close this ticket because it is out of the scope of the Mongo-Connector project.
