### ISSUE TITLE
How to pass authentication with elastic doc manager to ElasticSearch?

### ISSUE THREAD

**Issue by ekaM1** [mongodb-labs/mongo-connector#400]
I'm using ElasticSearch with shield. I can fetch data from mongo with mongo-connector, but when I try to pass data to ElasticSearch I'm getting error 

raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_me
ssage, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, 'security_
exception')
How I can pass username and password from mongo-connector to ElasticSearch. 

I have tried with the following configuration but it doesn't work.

{
 
    "authentication": {
        "__adminUsername": "ESusername",
        "__password": "password"
    },
	
	"docManagers": [
        {
            "docManager": "elastic_doc_manager",
            "targetURL": "ESusername:password@http://localhost:9200",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": 0
        }
    ]
}

**Comment by aherlihy** [comment]
Hello! It seems you are using the wrong format for your targetURL.

From https://elasticsearch-py.readthedocs.org/en/master/#ssl-and-authentication:

_# you can use RFC-1738 to specify the url
es = Elasticsearch(['https://user:secret@localhost:443'])_
