### ISSUE TITLE
How to load multiple mongodb collections into multiple documents in Solr?

### ISSUE THREAD

**Issue by NehaPateliya25** [mongodb-labs/mongo-connector#404]
I have many collections in mongoDB. I want every collections in mongoDB should get loaded in different documents in Solr using mongo-connector.How I can do this?

I am able to run  mongo-connector for only single solr document.

**Comment by aherlihy** [comment]
Hi! I'm not sure I understand your question.

Are you trying to load an entire collection into a single document in solr? Unfortunately, mongo-connector can't aggregate all documents from each collection into a single Solr document.

Are you having a problem with mongo-connector not loading all collections into solr, only some? If so, could you show me your configuration file?

If not, would you mind giving more details? Thank you!

**Comment by NehaPateliya25** [comment]
I will give an example.

Ex : 
MongoDB 'mydb' contains collection 'user_cl', 'address_cl', 'role_cl'
Solr 'mySolr' contains solrCore 'user', 'address', 'role'

I want mydb.user_cl get loaded into solr 'user' document, mydb.address_cl into  solr 'address' document and mydb.role_cl into solr 'role' document using mongo connector.

Can you please help me so that I can configure this.

**Comment by aherlihy** [comment]
Hello!

You are doing the correct thing right now, in order to get different collections into different solr cores you need to run multiple mongo-connectors.

FAQ Link: [How to load into several solr cores](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#how-can-i-load-several-solr-cores-with-mongo-connector)
