### ISSUE TITLE
Can I connect MongoDB with Cassandra or Oracle with the help of mongo-connecor ?

### ISSUE THREAD

**Issue by nikhar03** [mongodb-labs/mongo-connector#407]
I want to send mongodb data from MongoDB to Oracle or Cassandra instead of Elastic Search.How can I do that?

**Comment by aherlihy** [comment]
Hello!

Unfortunately mongodb-labs doesn't have a Cassandra or Oracle doc manager, however you can [write your own doc manager](https://github.com/mongodb-labs/mongo-connector/wiki/Writing-Your-Own-DocManager). Thank you!
