### ISSUE TITLE
Could not import mongo_connector.doc_managers.elastic_doc_manager

### ISSUE THREAD

**Issue by artursmolarek** [mongodb-labs/mongo-connector#408]
I have elastic_doc_manager installed, but I am still getting this error:

> root@server:~/elastic2-doc-manager# pip install elastic2-doc-manager
> Requirement already satisfied (use --upgrade to upgrade): elastic2-doc-manager in /usr/local/lib/python2.7/dist-packages/elastic2_doc_manager-0.1.0-py2.7.egg
> Requirement already satisfied (use --upgrade to upgrade): mongo-connector>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from elastic2-doc-manager)
> Requirement already satisfied (use --upgrade to upgrade): elasticsearch>=2.0.0,<3.0.0 in /usr/local/lib/python2.7/dist-packages (from elastic2-doc-manager)
> Cleaning up...

> root@server:~/elastic2-doc-manager# mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager
> No handlers could be found for logger "mongo_connector.util"
> Traceback (most recent call last):
>   File "/usr/local/bin/mongo-connector", line 9, in <module>
>     load_entry_point('mongo-connector==2.3', 'console_scripts', 'mongo-connector')()
>   File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
>     func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1041, in main
>     conf.parse_args()
>   File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 118, in parse_args
>     option, dict((k, values.get(k)) for k in option.cli_names))
>   File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 824, in apply_doc_managers
>     module = import_dm_by_name(dm['docManager'])
>   File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 814, in import_dm_by_name
>     "vailable doc managers." % full_name)
> mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.

Replica set is enabled.
OS: Ubuntu 14.04 Server
Python: 2.7.6

**Comment by artursmolarek** [comment]
I've found the solution:

Instead of:

`mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager`

we should use:

`mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager`

Would be great, if you can update wiki.

**Comment by aherlihy** [comment]
Edited the mongo-connector wiki to show both usages.
