### ISSUE TITLE
Upsert operation failing when _id is excluded from config

### ISSUE THREAD

**Issue by pdspicer** [mongodb-labs/mongo-connector#409]
Perhaps I am misunderstanding the latest documentation, but I have encountered an issue with keeping documents synchronized between MongoDB 3.2 and Elasticsearch 2.2 using mongo-connector >= 2.2 that seems to occur when using a configuration that limits the fields being synchronized. The error from the logs appears as such:
```
2016-03-15 06:03:51,378 [ERROR] mongo_connector.util:87 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/util.py", line 85, in wrapped func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector-2.3 py2.7.egg/mongo_connector/oplog_manager.py", line 261, in run docman.upsert(doc, ns, timestamp)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector-2.3-py2.7.egg/mongo_connector/util.py", line 32, in wrapped return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elastic2_doc_manager-0.1.0 py2.7.egg/mongo_connector/doc_managers/elastic2_doc_manager.py", line 148, in upset doc_id = u(doc.pop("_id"))
KeyError: '_id'
```
The issue appears to be that when field limits are listed in the mongo-connector configuration, the _id field is being deleted before upserting. The issue is resolved by including the _id field, but the necessity of specifying the _id field is contrary to my understanding of the documentation. If my interpretation is incorrect, then I apologize for raising this as an issue. I will try to include all relevant information below:
Configuration (abridged): 
```
{
    "mainAddress": "redacted",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 0,
    "continueOnError": false,

    "fields": ["field1",  "field2", "field3"],

    "namespaces": {
        "include": ["src"],
        "mapping": {
            "src": "dest"
        },
    },

    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "redacted",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "autoCommitInterval": 0
        }
    ]
}
```
Steps to reproduce:

1. Establish initial state: empty elasticsearch index/mapping at dest, pre-populate some docs in mongo src collection, delete oplog.timestamp
2. Start mongo-connector using config file (similar to defined above, specifically with regards to fields)
3. Observe that existing documents ARE synced with elasticsearch
4. Insert document into mongo src collection

expected result: new document is synced with elasticsearch, accessible at /dest/mapping/_id
actual result: document is not synced, error appears in log (as shown above)

Note that the expected result IS achieved if fields includes _id

**Comment by aherlihy** [comment]
Hello!

You have definitely found a bug with how we track fields with/without "_id" internally (the oplog manager code was expecting users to provide an "_id", but they shouldn't have to). I'm working on a fix and it shouldn't take very long. Thank you for the report!

**Comment by aherlihy** [comment]
Hello! [We have pushed the bug fix to master.](https://github.com/mongodb-labs/mongo-connector/commit/b6b4d767f93c7342e48c474113eae91b59b9467c) Thank you for the report!

**Comment by pdspicer** [comment]
Thank you for the fix!
