### ISSUE TITLE
is delta import allowed with mongo-connector?

### ISSUE THREAD

**Issue by rnjailamba** [mongodb-labs/mongo-connector#416]

**Comment by behackett** [comment]
Can you explain what you mean by delta import?

**Comment by rnjailamba** [comment]
A full import brings in all data since the beginning of time. 
A delta import gets data since last import.

**Comment by behackett** [comment]
mongo-connector keeps track of the last operation it replicated, writing to a file on disk. When mongo-connector is restarted it reads that file and picks up where it left off. However, if the last operation it synchronized is no longer in the oplog of the source mongod you have to resynchronize.

https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing%20the%20Connector
