### ISSUE TITLE
solr 5.5 luke path issue

### ISSUE THREAD

**Issue by brackmayhall** [mongodb-labs/mongo-connector#417]
The documentation for the solr lukehandler path seems to point to the wrong endpoint.

I had to use the following format
http://localhost:8983/solr/{collectionHere}/admin/luke/?show=schema&wt=json

instead of
http://localhost:8983/solr/admin/luke/?show=schema&wt=json

**Comment by behackett** [comment]
@aherlihy can you test with Solr 5.5? I notice we test in Travis against 4.9.1.

**Comment by brackmayhall** [comment]
I am having issues with testing. I have managed to work around the pathing issue. Now when I start up mongo-connector and attempt to insert (after setting up configs at noted in the solr doc manager wiki) my solr dashboard states that there is no luke configuration, but was one before i attempted to insert the mongo document

**Comment by aherlihy** [comment]
Hello! I've been testing mongo-connector with solr-5.5 and good news is that [all the tests pass](https://travis-ci.org/aherlihy/mongo-connector/builds/119805043). There are a few required changes:

1. The schema.xml file we provide in doc_managers did not work with solr-5.5. I've updated it so now it should work with both 5.5 and 4.9. If you were using that schema.xml, then I would suggest updating to [this one](https://github.com/mongodb-labs/mongo-connector/blob/cae9ee93b3227a1ee3af01b2d7b214fae7db9163/mongo_connector/doc_managers/schema.xml).

2. Solr-5.5 expects the core name to be appended to the solr address (as you mentioned). Previously we were setting SOLR_URL to 'http://localhost:8983/solr', and with 5.5 we have to set SOLR_URL to 'http://localhost:8983/solr/\<mycore\>'.

3. The way GridFS files are parsed has been changed. In 4.9 the data is stored in the 'content' field when copied to solr, in 5.5 it's copied to '\_text\_' and includes some meta-data.

My guess is that you need to update your schema.xml and make sure you're setting the solr url to include the core name. Let me know if you find any other changes.

**Comment by brackmayhall** [comment]
Sounds great. I will give the new schema a shot. I did end up getting things to injest by passing the uniqueid key through command line and not utilizing _id in the config.

**Comment by aherlihy** [comment]
Cool, let me know if you run into any issues. Thanks!
