### ISSUE TITLE
Multiple Elasticsearch Indices with same collection

### ISSUE THREAD

**Issue by hash-include** [mongodb-labs/mongo-connector#419]
Hi All

I am new to mongo-connector. Migrating from mongo-river to this project for syncing data between ES and Mongo. Can anyone please clarify below queries:

1. How to create a index with custom name, custom mapping from a single mongo db collection.
2. How to create two indices from same collection? 

Thanks
Sri Harsha

**Comment by aherlihy** [comment]
Hello!

If you want to change the name of the mapping, you can use https://github.com/mongodb-labs/mongo-connector/wiki/Configuration%20Options#namespacesmapping. 

I'm not sure what you mean by the second question. Do you want mongo-connector to copy the same collection twice, to two different indices?

**Comment by aherlihy** [comment]
I'm going to close this, feel free to reopen or file a new issue if you have more questions.
