### ISSUE TITLE
mongo-connector restarts indexing from scratch after service restart

### ISSUE THREAD

**Issue by apanimesh061** [mongodb-labs/mongo-connector#420]
I was indexed quite a few documents but for some reason I had to restart the service. As soon as I did that I noticed that index stopped updating and there were deletions being registered. They were actually not deletions, the indexing started from scratch and the existing documents were being replaced by the new ones, even though they were the same.

I confirmed this when I noticed that all the documents were updated to version 2, which means this document has been updated/reindexed.

How to avoid this?

**Comment by kubage88** [comment]
when i restart mongo-connector process, it stop to push data to elasticsearch, unless deleting oplog.timestamp,  but if i do this ,   mongo-connector will push data from beginning...
