### ISSUE TITLE
Writing a doc manager for Kafka

### ISSUE THREAD

**Issue by grindthemall** [mongodb-labs/mongo-connector#425]
I've been on a quest to be able to take from Mongo, and push into Kafka topics.

Is there a detailed doc on creating my own doc manager to accomplish this?

**Comment by behackett** [comment]
There is:

https://github.com/mongodb-labs/mongo-connector/wiki/Writing%20Your%20Own%20DocManager

**Comment by grindthemall** [comment]
Thanks for that, somehow I missed the obvious :)

**Comment by behackett** [comment]
No worries. Let us know if you have any further questions.

**Comment by grindthemall** [comment]
I do have one - reading through the Doc Manager guide, it speaks to various actions on the target system - Kafka is a two-way messaging system, but it doesn't work referentially like Elastic or Mongo.

I basically push messages into topics, and read an "offset" that tells me where I was last reading a given topic (the Kafka equivalent of an Elasticsearch Index - sort of).

So, basically Kafka from the Doc Manager's point of view is really a "one-way" communication.  How should I handle those sections that would try to "read" or "update" information In Kafka, since those aren't really valid functions?

**Comment by llvtt** [comment]
@grindthemall, it's up to you. If a document gets updated in MongoDB, what do you want to happen in Kafka? If nothing should happen, you don't have to do anything for the `update` method. If you want to retrieve and push the latest version of the document to Kafka from MongoDB, you'll need to create a `pymongo.mongo_client.MongoClient`, fetch the document by `_id`, then push the fetched document to Kafka.

If the `search` method cannot be implemented or doesn't make any sense, you can just return an empty list.

Generally, if a method doesn't make any sense, you can define the method and give it a body of `pass` or return an empty value as appropriate.

**Comment by grindthemall** [comment]
It's up to my client consumers to recognize that a second message came through with the same source doc _id. So I'm not worried about injecting updates.

I finally got a complete doc manager written, however following the directions on the API Doc Manager page, I get the following error:

```
[user@mongotoes001 docman_project]$ mongo-connector -m mongo001:27017 -t kafka.service.consul:9092 -d kafka_doc_manager --batch-size=1000 -n SharedDB.DeviceLogs -g devicelogs.SharedDB -o logdataoplog4.log
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 1041, in main
    conf.parse_args()
  File "/usr/lib/python2.7/site-packages/mongo_connector/config.py", line 118, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 824, in apply_doc_managers
    module = import_dm_by_name(dm['docManager'])
  File "/usr/lib/python2.7/site-packages/mongo_connector/connector.py", line 814, in import_dm_by_name
    "vailable doc managers." % full_name)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.kafka_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.
```

I have verified I am in the right directory, the directory tree is created as mentioned above, mongo-connector was installed via "pip install mongo-connector", I've set the PYTHONPATH=.

Oddly enough, if I try running mongo-connector with one of your plugins from the same base directory it has the same problem.  The directory where I launch mongo-connector is /home/user/docman_project/

Any suggestions?  Is there some Python path setup issues I'm not recognizing?

**Comment by grindthemall** [comment]
Of what type is "doc" as found in any of the existing document managers?  I'm having a heck of a time converting my incoming data to proper (utf-8) json to send into Kafka.  For some reason I just can't hunt down where the "doc" field is defined before it gets passed to the upsert function.

**Comment by llvtt** [comment]
"doc" is a Python dictionary representing the MongoDB document. Keep in
mind that "doc" might have special BSON types that don't have JSON
equivalents. You might find "json_util.dumps" from the "bson" package to be
useful:
http://api.mongodb.org/python/current/api/bson/json_util.html?highlight=json_util#bson.json_util.dumps

**Comment by grindthemall** [comment]
Ok, that function and type is exactly what I was looking for.  It solved my last remaining issues.

I think my connector is just about ready for production (I'm testing a run with several million messages going through it).

If I deem it worthy, how would I add it into your document managers collection (probably as an experimental module)?  I'm not that adept with Git, so I'm very hesitant to try branching it.

**Comment by avitashpurohit** [comment]
@llvtt How do you read Mongo Connection Settings from config json? The doc manager does not receive them as arguments I think.
