### ISSUE TITLE
No handlers could be found for logger "mongo_connector.util"

### ISSUE THREAD

**Issue by wmurmann** [mongodb-labs/mongo-connector#427]
I can do a basic connection with:

mongo-connector -m localhost:27017 -t elasticserver:9200 -d elastic2-doc-manager

however when I try to do more advanced settings like so:

mongo-connector -m localhost:27017 -t  elasticserver:9200 -d elastic2-doc-manager -n database.collection -i field1,field2,field3

I get:

No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.3', 'console_scripts', 'mongo-connector')()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 1041, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 118, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 824, in apply_doc_managers
    module = import_dm_by_name(dm['docManager'])
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 814, in import_dm_by_name
    "vailable doc managers." % full_name)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2-doc-manager. It could be that this doc manager has                      been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the READ                     ME for a list of available doc managers.

Where am I messing up?

**Comment by aherlihy** [comment]
You should use "elastic2_doc_manager" instead of "elastic2-doc-manager", see [here](https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-ElasticSearch#the-basics) for usage.

Let me know if that doesn't help!

**Comment by wmurmann** [comment]
Shoot I missed that. It helps to an extent. Now it just hangs after I choose to connect. I double check my db and field names. There are no logs for any errors. Here's an example.
![hang](https://cloud.githubusercontent.com/assets/4755316/14447189/0813f27a-0012-11e6-86aa-6604318f66b7.png)

**Comment by aherlihy** [comment]
Have you checked that your documents aren't being copied over to elastic?

If they aren't, have you checked for any errors in the logs? Both mongo-connector.log and the elastic logs.

When mongo-connector is running successfully in the foreground it will look just like what you sent me.

**Comment by wmurmann** [comment]
Yes when I do a full index of every database without arguments the following folder
`/var/lib/elasticsearch/elasticsearch/nodes/0/indices`
holds all my data and it checks out.

No Logs on either server show any problems. I takes about 15 seconds for it to index all my files, the index with arguments hangs for over an hour before my ssh terminal goes to sleep. Could it be a compatibility problem. I'm running elasticsearch 2.0, current mongo-connector and mongo 3.0.2. ?

I am able to use some config options like --tz-aware but namespace and fields give me issues.
