### ISSUE TITLE
How to use mongo-connector with mongos?

### ISSUE THREAD

**Issue by vipsql** [mongodb-labs/mongo-connector#430]
"replSetGetStatus is not supported through mongos",so the mongo-connector Failed with "OperationFailure: not authorized on local to execute command { find: "oplog.rs", filter: {}, limit: 1, singleBatch: true }"!!
 how can i solve?

**Comment by aherlihy** [comment]
Hello!

You cannot run mongo-connector without direct access to the mongo shards. Mongo-Connector must be able to read the oplogs, which live on the shards and are not accessible through mongos (i.e. "not authorized on local to execute command").

**Comment by aherlihy** [comment]
I've added a FAQ entry: https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#why-cant-i-use-mongo-connector-with-only-the-mongos

**Comment by vipsql** [comment]
@aherlihy  thanks
