### ISSUE TITLE
Date format in elastic search is different from Mongo

### ISSUE THREAD

**Issue by gsfeng** [mongodb-labs/mongo-connector#434]
Hi,

After the data is transferred from  Mongo to Elastic Search, I noticed that the date format changed.

i.e. 
In Mongo, it is stored as ISODate("2016-03-01T01:00:00.000Z")
where as it appear as 2016-03-01T01:00:00.000000 in elastic search

Is there a way to retain the format (yyyy-MM-ddTHH:mm:ss.SSSZ) as in Mongo?

**Comment by aherlihy** [comment]
Hello!

Sorry for the delay in getting back to you.  Mongo-connector passes python datetime objects straight into the Elastic Python driver, which handles the conversion into Elastic Search dates. There are no Mongo-Connector configuration options that specifically handle date format.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html The Elastic documentation may be helpful for you here.

**Comment by aherlihy** [comment]
Hi, I'm going to close this ticket due to inactivity but please feel free to reopen or file a new ticket if you have more questions. Thanks!
