### ISSUE TITLE
Indexing referenced mongodb documents

### ISSUE THREAD

**Issue by prasadh13** [mongodb-labs/mongo-connector#435]
I have my documents like this - 
{
    _id:ObjectId("56c35a782abeaed0564edfa9"),
    //other fields
   ...
   ..
   field:ObjectId("56c359fa2abeaed0564edfa8") //reference field of doc of another collection in this doc
}
So is it possible to index the fields of the referenced document?

**Comment by aherlihy** [comment]
Hi,

Unfortunately there is no way to do what you are asking. Mongo-Connector does not do joins.
