### ISSUE TITLE
mongo_connector.errors.InvalidConfiguration:

### ISSUE THREAD

**Issue by vgsampathkumar** [mongodb-labs/mongo-connector#449]
Hi Guys

I am trying to connect the mongodb and neo4j using the neo doc manager and mongo connector as mentioned in the below link 

https://github.com/neo4j-contrib/neo4j_doc_manager

One of the step in starting the service is as below 

mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager

when i try to execute it as mentioned in the above link i am getting this error 

mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.neo4j_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers.

I have setup the PATH  for this ; not sure whats the problem .Please help i am draining out with all solutions.Looks silly to me .This is what i have installed 

Python 3.5
Noe4j 2.3.3
Mongo 3.2.4

Please help 

Sampath

**Comment by behackett** [comment]
Hi. We don't maintain the neo4j doc manager. Please open a ticket in its ticket tracker.

https://github.com/neo4j-contrib/neo4j_doc_manager/issues
