### ISSUE TITLE
MongoDB + GridFS + Solr

### ISSUE THREAD

**Issue by cristianoub** [mongodb-labs/mongo-connector#450]
Hi, I have an project where I need to send to Solr the documents(files like excel, word, pdf and etc) stored using GridFS in Mongodb to Solr. The mongo-connector worked perfect to documents that aren`t files but not to pdf`s and etc. I would like know if mongo-connector Does this.

**Comment by behackett** [comment]
That should work. See https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#namespacesgridfs

**Comment by cristianoub** [comment]
Its worked perfect tks Behackett!
