### ISSUE TITLE
Support for Elastic 5.0

### ISSUE THREAD

**Issue by kawaljeet** [mongodb-labs/mongo-connector#453]
Hi Team,
Elastic 5.0 alpha 2 is already there. We might soon be getting the release version.
Just wanted to check if you have any plans of supporting Elastic 5.0 ? and by when ?
Thanks,

**Comment by behackett** [comment]
Does Elastic 5 require a new elastic python driver? If not, there shouldn't be any changes required. I would be surprised if they broke backward compatibility again after they just broke backward compatibility last year.

**Comment by marcinkubica** [comment]
AFAIK breaking changes are coming. They already said even current alpha
version indexes wont be compatible with GA

-- 
Sent from Gmail Mobile

**Comment by kawaljeet** [comment]
Thanks a lot @behackett  .and .. @marcinkubica  ..
@behackett  https://github.com/elastic/elasticsearch-py states the updated version of 5.0 will be there. 
Any comments / suggestions ?

**Comment by behackett** [comment]
I see that now. I have to say I'm surprised. Why would you break backward compatibility and cause users to have to rewrite their applications every 6-12 months?

**Comment by marcinkubica** [comment]
I guess sometimes you can't progress further without introducing
an incompatible change. ES5.0 promises 25% speed boost - probably worth a
change.

Also, in today's world if you are not agile enough to be ready for a
rewrite on a short notice and just happy with no boost changes within 6 or
12 month periodn then well, then probably something needs to be adressed
here and there.

Not bitching, just my 5 cents. ;)



-- 
Sent from Gmail Mobile

**Comment by ShaneHarvey** [comment]
With the recent [release of Elasticsearch-py 5.0.0](https://github.com/elastic/elasticsearch-py/commit/ae0073c8ca7e24d237ffd56fba495ed409081bf4) I tested the elastic2-doc-manager master and Elasticsearch server version 5.0.0-rc1 and the tests pass after a [trivial change](https://github.com/mongodb-labs/elastic2-doc-manager/commit/fe9440df652fede11226b38dbe4cd24e1cfcce84) to remove a `filtered` query: https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170269350 

The tests also passed with Elasticsearch-py 5.0.0, elastic2-doc-manager master, and Elasticsearch server version 2.2.0 which you can see here: https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170212353.

The other way does not work. Elasticsearch-py 2.4.0, elastic2-doc-manager master, and Elasticsearch server version 5.0.0-rc1 fails which you can see here: https://travis-ci.org/ShaneHarvey/elastic2-doc-manager/builds/170255998

For now it looks like you can test out using mongo-connector/elastic2-doc-manager (master) with Elasticsearch 5 by upgrading elasticsearch-py manually:
```
$ pip install mongo-connector
$ pip install https://github.com/mongodb-labs/elastic2-doc-manager/archive/master.zip
$ pip install --upgrade elasticsearch-py==5.0.0
$ # run mongo-connector with an elasticsearch 5.0.0 target
```

Please let us know if you run into any issues!

**Comment by kawaljeet** [comment]
Thanks a lot @ShaneHarvey .. for the information shared. will try it out and keep you posted..

**Comment by zqadora1** [comment]
I have run in the following issue when running

 pip install --upgrade elasticsearch-py==5.0.0
Collecting elasticsearch-py==5.0.0
  Could not find a version that satisfies the requirement elasticsearch-py==5.0.0 (from versions: )
No matching distribution found for elasticsearch-py==5.0.0

**Comment by ShaneHarvey** [comment]
Sorry for the typo, it should be:
`pip install --upgrade elasticsearch==5.0.0`
or:
`pip install --upgrade 'elasticsearch>=5.0.0,<6.0.0'`

**Comment by zqadora1** [comment]
that worked.  

Now I get  {'index': {'error': {'reason': 'Limit of total fields [1000] in index [synergy_clone] has been exceeded', 'type': 'illegal_argument_exception'}, 'status': 400 ...

This will be a full import, so what is the best way to  change the bulkSize or ignore it all together?

**Comment by ShaneHarvey** [comment]
This is not an error related to bulkSize. I think you are running into https://github.com/elastic/elasticsearch/pull/17357. Your `synergy_clone` database in MongoDB has so many unique fields that it is hitting the default 1000 fields limit added in Elasticsearch 5.0.

What is your reason for having so many unique fields?

**Comment by zqadora1** [comment]
It is not in our control. the data is exported from an informix database into mongodb.

**Comment by ShaneHarvey** [comment]
Elasticsearch 5.x support had been released as part of the elastic2-doc-manager version 0.3.0. For installation and usage see https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Elasticsearch#installation.
