### ISSUE TITLE
exclude_fields in the config file

### ISSUE THREAD

**Issue by sharok** [mongodb-labs/mongo-connector#454]
I am trying to use `exclude_fields` in a config file:
```
{
  "exclude_fields": "media"
}
```

but, when I run connector I get message:
> WARNING:root:Unrecognized option: exclude_fields

I have found in the source the following line:
`  exclude_fields=config['exclude_fields']`
it means that it's supported.   

Can somebody confirm can I use it or not? or may be I've made something wrong.

**Comment by behackett** [comment]
The exclude_fields option hasn't been released yet. To use it you have to use mongo-connector from git master.

**Comment by sharok** [comment]
Thanks for the answer.
