### ISSUE TITLE
Elasticsearch doc manager should accept multiple hosts

### ISSUE THREAD

**Issue by atomicopossum** [mongodb-labs/mongo-connector#456]
The ES doc manager only allows a single host to be specified, even though the underlying library supports passing in a list of HA nodes. The doc manager should expose this functionality (probably by allowing targetURL to accept a list of hosts).

This feature was referenced in #359 and #275.

**Comment by ShaneHarvey** [comment]
There is an on-going pull request (https://github.com/mongodb-labs/elastic2-doc-manager/pull/17) that adds the ability to give a list of hosts to elastic via the `targetURL` option. Part of the pull request also turns on [Elasticsearch sniffing](http://elasticsearch-py.readthedocs.io/en/master/index.html#sniffing) by default. So:

```json
{
    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": ["somehost:9200", "anotherhost:9200"]
        }
    ]
}
```
becomes:
```json
{
    "docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": ["somehost:9200", "anotherhost:9200"],
            "clientOptions": {
                "sniff_on_start": true,
                "sniff_on_connection_fail": true,
                "sniffer_timeout": 60
            }
        }
    ]
}
```

If you have any questions or concerns feel free to comment on the pull request.

**Comment by ShaneHarvey** [comment]
Support for multiple Elasticsearch hosts has been released in elastic-doc-manager/elastic2-doc-manager versions 0.3.0. To use, see https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Elasticsearch#connecting-to-multiple-elasticsearch-hosts
