### ISSUE TITLE
mongo-connector works with oldest oplog entry

### ISSUE THREAD

**Issue by EduVal** [mongodb-labs/mongo-connector#460]
Hello,

it seems to me, that mongo-connector doesn't save the latest mongodb oplog entry in oplog.timestamp, but the oldest point. 

For example:
sudo mongo-connector -m <origin_mongodb_node>:27017 -t mongodb://<mongodb_user:mongodb_password>@<target_mongodb_node>:27017 -d mongo_doc_manager -v --stdout  -a <origin_mongodb_user> -p <origin_mongodb_password> --batch-size 100 --no-dump

It create a file oplog.timestamp
["Collection(Database(MongoClient(['db-dev-xxx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017
', u'db-dev-xxx.lhotse.ov.otto.de:27017']), u'local'), u'oplog.rs')", 6288710523760410669]

In my point of view the number 6288710523760410669 should be the current / latest oplog entry, but 
when you start mongo-connector again it  prints an unix timestamp =1464204519 , which is pointing to the oldest oplog entry of origin database.

2016-05-26 16:59:45,165 [DEBUG] mongo_connector.oplog_manager:747 - OplogThread: reading last checkpoint as Timestamp(1464204519, 45) 
2016-05-26 16:59:47,910 [ERROR] mongo_connector.oplog_manager:203 - OplogThread: Last entry no longer in oplog cannot recover! Collection(Database(MongoClient(['db-dev-xxx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017']), u'local'), u'oplog.rs')

other informations:
sudo python --version => Python 2.7.6
mongodb version => 3.0.10 
mongodb storage engine => wiredtiger

How it ist possible to convert the last checkpoint (6288710523760410669) in oplog.timestamp file to unix timestamp (1464204519) format in python?

Thank you for helping
Eduard

**Comment by llvtt** [comment]
Mongo connector should always have the latest timestamp from the oplog, since it sorts on `$natural` descending: https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L648-L650

To convert the number that mongo-connector stores as the timestamp into seconds since the Unix epoch:

    timestamp >> 32 & 0xffffffff

You can also covert the number back into a BSON Timestamp by importing the approprate function from mongo_connector:

from mongo_connector.util import long_to_bson_ts

    print(long_to_bson_ts(timestamp_number))

Hope this helps!

**Comment by EduVal** [comment]
Thank you for helping. It helps me to continue my task, but for me it seems very strange...

If I run:
sudo mongo-connector -m db-dev-xxx.lhotse.ov.otto.de:27017 -t mongodb://user:passw@db-dev-xxx.lhotse.ov.otto.de:27017 -d mongo_doc_manager -v --stdout  -a user -p password --oplog-ts /tmp/oplog --batch-size 100 --no-dump

It create me that oplog-ts file, that points to 14 of June:
["Collection(Database(MongoClient([u'db-dev-xxx.lhotse.ov.otto.de:27017', 'db-dev-xxx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017']), u'local'), u'oplog.rs')", 6296061519201304674]

But in mongodb oplog collection you see current timestamps.
develop_name_RS:PRIMARY> db.oplog.rs.find({},{"ts":1}).sort({$natural: -1})
{ "ts" : Timestamp(1465996771, 4) }
{ "ts" : Timestamp(1465996771, 3) }
{ "ts" : Timestamp(1465996771, 2) }
{ "ts" : Timestamp(1465996771, 1) }
{ "ts" : Timestamp(1465996770, 9) }
{ "ts" : Timestamp(1465996770, 8) }

I'm wondering me all the time too, but it is really strange.

sudo python --version
Python 2.7.6

kind regards

**Comment by EduVal** [comment]
Hello,

sorry but I have another question.
The oplog thread is reading last checkpoint as Timestamp(1465996770, 0) . But it isn't available. In oplog collection in mongodb database is an entry like this "{ "ts" : Timestamp(1465996770, 1) }". How mongo-connector create the second number after unix timestamp? I couldn't find anything in oplog file. 
 

sudo mongo-connector -m db-dev-x.lhotse.ov.otto.de:27017 -t user:pass@db-dev-xx.lhotse.ov.otto.de:27017 -d mongo_doc_manager -v --stdout  -a mdbadmin -p ci4ever! --oplog-ts ./oplog --batch-size 100 --no-dump

2016-06-15 17:09:45,928 [INFO] mongo_connector.connector:1060 - Beginning Mongo Connector
2016-06-15 17:09:47,246 [INFO] mongo_connector.oplog_manager:92 - OplogThread: Initializing oplog thread
2016-06-15 17:09:47,300 [INFO] mongo_connector.connector:296 - MongoConnector: Starting connection thread MongoClient([u'db-dev-x.lhotse.ov.otto.de:27017', 'db-dev-xx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017'])
2016-06-15 17:09:47,301 [DEBUG] mongo_connector.oplog_manager:194 - OplogThread: Run thread started
2016-06-15 17:09:47,301 [DEBUG] mongo_connector.oplog_manager:196 - OplogThread: Getting cursor
2016-06-15 17:09:47,301 [DEBUG] mongo_connector.oplog_manager:747 - OplogThread: reading last checkpoint as Timestamp(1465996770, 0) 
2016-06-15 17:09:47,302 [DEBUG] mongo_connector.oplog_manager:731 - OplogThread: oplog checkpoint updated to Timestamp(1465996770, 0)
2016-06-15 17:09:50,430 [ERROR] mongo_connector.oplog_manager:203 - OplogThread: Last entry no longer in oplog cannot recover! Collection(Database(MongoClient([u'db-dev-x.lhotse.ov.otto.de:27017', 'db-dev-xx.lhotse.ov.otto.de:27017', u'db-dev-xxx.lhotse.ov.otto.de:27017']), u'local'), u'oplog.rs')


thank you in advance

**Comment by llvtt** [comment]
This is how mongo-connector turns timestamps into longs: https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/util.py#L48-L54. See the function underneath it for the reverse.

The message "Last entry no longer in oplog cannot recover!" means that the latest timestamp mongo-connector knows about is no longer in the oplog. A resync is now required. See https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing%20the%20Connector

**Comment by winder** [comment]
@llvtt I'm getting a `Last entry no longer in oplog cannot recover!` error even though the last entry definitely *is* in the oplog. We have a particularly large oplog at around 50GiB. I noticed when querying the oplog directly for the timestamp in question it takes quite a while to create the cursor, so I'm wondering if there is a timeout happening somewhere.

**Comment by llvtt** [comment]
This is where mongo-connector is attempting to pick up from where it left off: https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L716-L722. We already have the timestamp from the oplog, so the issue isn't a timeout with the cursor. The issue is that when mongo-connector tried to find the oplog entry matching the given timestamp from the progress file, it found one that occured afterwards. It therefore assumes that the entry does not exist anymore.

When you queried the oplog manually, did you also include the increment part of the timestamp (i.e. the second number in Timestamp(x, y))? As a sanity check, you can try running something similar to what mongo-connector does to see if you can retrieve the timestamp:


    from pymongo import MongoClient, CursorType
    
    from mongo_connector.util import long_to_bson_ts
    
    ts_long = ...  # Timestamp from oplog progress file as an int
    timestamp = long_to_bson_ts(ts_long)
    
    client = MongoClient("mongodb://<host>:<port>/?replicaSet=<rs name>")
    oplog = client.local.oplog.rs
    
    cursor = oplog.find(
        {"ts": {"$gte": timestamp}},
        cursor_type=CursorType.TAILABLE_AWAIT)
    cursor.add_option(8)  # enable oplog replay
    
    # First entry in the cursor should be the same as the given timestamp.
    assert next(cursor).get("ts") == timestamp

**Comment by winder** [comment]
I'll give that python snippet a try. To test out a query manually I ran this:
```
use local;
db.oplog.rs.find({ns:'my_db.my_collection', ts:{$gte: Timestamp(1465910124, 0)}});
```

```
>>>  time mongo-prod < test
MongoDB shell version: 3.2.4
connecting to: core-mongo.traackr.com/admin
switched to db local
Cannot use 'commands' readMode, degrading to 'legacy' mode
....
< oplog stuff >
...
Type "it" for more
bye

real	26m21.349s
user	0m0.055s
sys	0m0.034s
```

It took a lot longer than I was expecting.

**Comment by EduVal** [comment]
Hi,

I'm wondering about the how-to in section "Using mongodump and mongo-connector together"
https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20MongoDB

It describes that my oplog.timestamp should point to the latest (not the first) oplog entry. But after starting and stopping it, it points to the first oplog entry. That's why I have to wait until the whole oplog will be processed to point to the latest entry.

What is the expected behaviour ? 

Regards
Eduard

**Comment by llvtt** [comment]
The timestamp file is only periodically updated, so examining the file after mongo-connector has been running doesn't guarantee that the timestamp is the latest one: https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#my-oplog-progress-file-always-seems-really-out-of-date-whats-going-on

The instructions in https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20MongoDB assume that the oplog timestamp file doesn't yet exist, and that you are running mongo-connector for the first time in order to transfer documents to another MongoDB cluster.

**Comment by EduVal** [comment]
Ok now I understand the meaning of how-to documentation.
Thank you for helping

**Comment by bhyde** [comment]
The instructions in https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20MongoDB which leverage mongo{dump,restore} did not work out for me; but I was able to work around the problem.

Running mongo-connector for a moment (with --no-dump) creates timestamp file.  But it has the a very old entry in the oplog.  An entry that will almost certainly be discarded before you can finish doing the mongo{dump,restore}.

So my work around was to set the timestamp file, by hand, so the timestamp was just before I started the mongodump.

I was able to do that by finding the most recent entry in oplog.

Here for example I'm getting the oldest and newest entries (in natural order) and grabbing their timestamps.
```
mc = MongoClient(source_mongod_url)
op = mc.local['oplog.rs']
start, end = ( op.find({'op':{'$ne': 'n'}}, {'ts':1}).sort('$natural', pymongo.ASCENDING).next()['ts'] , op.find({'op':{'$ne': 'n'}}, {'ts':1}).sort('$natural', pymongo.DESCENDING).next()['ts'])
```

You can do things like: ```print end.as_datetime()``` to print roughly the time that last entry was made.   or ```print end.as_datatime() - start.as_datatime()``` to see how large the oplog is from a time perspective.

Convert the end into the very large integer found in the foo.timestamp file used to point into the oplog by doing: ```bson_ts_to_long(end)```.  The bson_ts_to_long routine is in the utils.py file.   Take that integer and replace the one you got by following the instructions as written.

Maybe there is some less hacky way to achieve this goal; but I'm hoping I'm happy now.
