### ISSUE TITLE
Gracefully shutdown on SIGTERM and SIGINT

### ISSUE THREAD

**Issue by luisobo** [mongodb-labs/mongo-connector#461]
Hi there,

I'm not 100% sure but as far as I can tell, mongo-connector does not handle SIGSTOP. I'd expect it to listen to that signal and gracefully stop the threads, save the latest state to disk and exit. In SIGSTOP is not handled the only option is to use SIGKILL, which can potentially leave the system in an inconsistent state.

I'm using mongo-connector 2.3.0 with elastic2_doc_manager 0.1.0.

**Comment by llvtt** [comment]
According to the man pages for BSD and Linux (http://www.unix.com/man-page/FreeBSD/3/signal/ and http://man7.org/linux/man-pages/man7/signal.7.html), SIGSTOP cannot be caught or ignored.

SIGKILL is the normal way to stop mongo-connector.

**Comment by luisobo** [comment]
@llvtt you're 100% right. I meant SIGTERM, which is the signal that docker issues on docker stop. I edited the title, thanks. 

Regardless of the signal, the critical part is shutting down gracefully, which would include:
- closing connections
- killing threads
- writing progress file to disk
- exit with a status code of 0

Right now it takes a while for the system to shutdown. Seems that the system ignores SIGTERM (when running on docker) or SIGINT (when running in a console and doing Control+C) and only when it times out a SIGKILL is emitted. The process ends but with a status of 137 and I'm not sure if the progress file is properly persisted.

**Comment by llvtt** [comment]
Oops, I got my signal wrong as well. I meant SIGINT is the normal way to stop the connector.

If the connector is not responding to a SIGINT within a minute or two, then something is wrong. Do you have the logs from mongo-connector available from a time when it wasn't responding?
