### ISSUE TITLE
Update of nested properties filtered out

### ISSUE THREAD

**Issue by robertaistleitner** [mongodb-labs/mongo-connector#477]
I have an issue when using nested properties, it seems the ```filter_oplog_entry``` method in the oplog manager filters out valid updates with $set on nested properties.

I defined my fields like this, which works well for initial synchronization:
```
--fields _id,prop1,prop2,complexprop1.subprop1,complexprop1.subprop2
```

The problem is when I'm updating data in mongodb using $set updates with a nested property, e.g.
```
db.coll.update({"_id": ObjectId(...)}, {$set: {"complexprop1.subprop1": "value1"}})
```
it's not updated in elasticsearch due to the ```filter_oplog_entry``` method, which is not handling this case. In general this function is kind of hard to read, because it's returning something, but also modifying the passed parameter and all of this in some different ways so when reading it it's hard to understand what it actually does.

**Comment by robertaistleitner** [comment]
Another little note: I already did a fix on my own for a previous version and created a pull-request as well, but it was rejected because there was another solution for it.. You can find the pull-request here: #382

**Comment by ShaneHarvey** [comment]
Fixed by https://github.com/mongodb-labs/mongo-connector/commit/293e3d45d4def8920e980847e4af8a57382b097a
