### ISSUE TITLE
Support wildcard characters in namespace include/exclude options

### ISSUE THREAD

**Issue by PeterBackman** [mongodb-labs/mongo-connector#480]
The default behaviour of mongo-connector is to automatically synchronize all collections in all databases with elasticsearch (or other systems). This is really powerful but in our system we have different databases in MongoDB with different purposes. Due to this we only want to synchronize a subset of databases with elasticsearch. This is possible by specifying namespace.include configuration but this kind of micro management of collections is cumbersome since our system will add/remove collections based on user input.

It would be really great if one could limit the amount of databases to synchronize without having to specify every collection to synchronize.

**Comment by llvtt** [comment]
Perhaps `namespaces.include` and `namespaces.exclude` could accept wildcard characters like `*` that match anything. For example, one could specify `{"namespaces": {"include": ["foo.*"]}}` to mean "synchronize all collections in the `foo` database". Would that fit your use case? This is something that has been requested before in #285.

**Comment by PeterBackman** [comment]
Sorry didn't see #285. This solution with wildcards and an exclude option would would work fine for us for our new development.

Would namespace.mapping still be hardcoded names or could that be extended as well? Either way this would simplify a lot for us.

**Comment by llvtt** [comment]
The scope of this feature is just using wildcards in namespace include/exclude. Extending namespace mappings to map names like `foo.*` to `bar.*` is a separate issue. Is this something you're interested in as well? If so, please feel free to open another issue and I'll take a look.

**Comment by weixili** [comment]
Hi, I submitted a new issue about the namespaces.mapping #488. Please have a look at it.

**Comment by weixili** [comment]
I thought to implement this feature dynamically. For example, if there are `foo.a`, `foo.b` and `foo.c` in our db and we specify to include `foo.*` in the mongo-connector configuration, now we have a new collection created called `foo.d`, we dont need to restart mongo-connector but the change can be detected automatically. But when I had a look at the code handling cursors, it seems like it needs a real big change in the code. 

It seems like the current code is more like a static way, am I right?
It would be much easier to support wildcard in a static way. If we have a new collection, it has to restart the mongo-connector to let it knows the change. Would that be acceptable?

**Comment by llvtt** [comment]
@weixili, I believe this feature would include picking up automatically a new collection that was created after the connector has been started. No one has started work on this feature yet, but I don't think it will be too tricky.

**Comment by letsgolesco** [comment]
Question: are you guys planning on supporting wild cards for collections only, or for databases as well?

I have a use case where I have the same collections in multiple databases, and I'd like those collections to be included from every database.

Right now my config's `namespaces.include` would look like:
`["db1.collection1", "db1.collection2", "db2.collection1", "db2.collection2"]`

But I'd like to do this:
`["*.collection1", "*.collection2"]`

Will that be possible with the current state of #495?

**Comment by llvtt** [comment]
@letsgolesco, yes, that should be supported in that PR as well. The goal is to support a single wildcard character anywhere in a namespace, which could be all or some of the database or collection name (but not both).

**Comment by ShaneHarvey** [comment]
Thanks to @weixili, mongo-connector now has support for excluding namespaces as well as using a wildcard in namespaces.include/exclude/mapping. [See the wiki for details](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces).
