### ISSUE TITLE
DocManager OperationFailure can lose updates

### ISSUE THREAD

**Issue by rectalogic** [mongodb-labs/mongo-connector#484]
If a Doc Manager fails to upsert/update and raises OperationFailure, mongo-connector continues processing further oplog entries and updates oplog.timestamp - so the failed operation will never be retried and the target system will contain different data from mongodb.

See #479 for a fix.

**Comment by llvtt** [comment]
Closing this per the discussion in #479 (conclusion summary: The doc manager should take care of retrying operations it knows to be retry-able).
