### ISSUE TITLE
Reduce Shard Number to 1

### ISSUE THREAD

**Issue by Kalleos2** [mongodb-labs/mongo-connector#486]
Hi,

after I run the mongodb-connector each mongodb database is stored in elastic search on 10 shards.
How can I reduce the amount to only a single shard? 
I know that having more shards improves writing performance. But I think having only one shard imporoves the reading perforance
So how to set shard numbers to 1?

thanks

**Comment by llvtt** [comment]
The elastic doc manager creates indexes only by indexing documents into them; the indexes are created with whatever the default settings are. You can change the settings like this: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#indices-update-settings.
