### ISSUE TITLE
Extend namespaces.mapping to support wildcards

### ISSUE THREAD

**Issue by weixili** [mongodb-labs/mongo-connector#488]
If we have features that supporting wildcards in namespaces.include/exclude ( #285 #480 ), it would be good that also extending namespaces.mapping to support similar behaviors. In our case, we may have different index for different collections, but it would be nice that we dont need to specify all collections one by one. 

For example, we would like it supports mapping like: `foo.*` to `bar_*.someting`, so if we have two collections `foo.a` and `foo.b` will map to `bar_a.something` and `bar_b.something`.

**Comment by llvtt** [comment]
I think this makes sense. So, the destination collection/type will have a name that is the value from the namespace mapping, with the wildcard character (`*`) replaced by whatever the wildcard character matched in the source. I believe this matches your examples above.

**Comment by ShaneHarvey** [comment]
mongo-connector now has support for excluding namespaces as well as using a wildcard in namespaces.include/exclude/mapping. [See the wiki for details](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces). Thanks @weixili!
