### ISSUE TITLE
maintain oplog during dump

### ISSUE THREAD

**Issue by dfaerch** [mongodb-labs/mongo-connector#489]
During a 16 hour bulk import to Solr, i noticed that the oplog is created, but never filled in this phase. This means, that when you restart mongo-connector before the dump is complete, mongo-connector restarts the import. 

It would be a nice feature to be able to restart service, during dump/import and continue where it left off.

**Comment by llvtt** [comment]
What do you mean by "the oplog is created"? Mongo connector cannot resume a dump from where it left off, because the contents of the dump could have changed significantly beyond the point recorded by the oplog.

**Comment by dfaerch** [comment]
By "the oplog is created" I mean, "the oplog *file* is created but empty". 

Mongo and Solr are quite new to me, so i can offer no suggestions. I was just hoping that there might be a way to record the progress, so one didn't have to restart in the event of a crash. If it cant be done, well, thats that :)

**Comment by llvtt** [comment]
Yeah, unfortunately the dump phase cannot be restarted; it has to be completed all in one go. After that is done, though, you can restart the connector and it should pick back up from where it left off, as long as the timestamp in the oplog file is still in the replica set oplog somewhere.
