### ISSUE TITLE
Question: Will mongo-connector pick up new namespaces in config during run time

### ISSUE THREAD

**Issue by gsfeng** [mongodb-labs/mongo-connector#491]
Hi,

If the mongo-connector is running, and I added a new namespace in the config, will it pick up the new namespace to sync the data over? 

If not, is there is a way to achieve this?

Thanks.

**Comment by llvtt** [comment]
Mongo connector should pick up new namespaces while running, as long as those namespaces were provided to `--namespace-set`.
