### ISSUE TITLE
Select fields per namespace

### ISSUE THREAD

**Issue by AdallomRoy** [mongodb-labs/mongo-connector#497]
If I want to sync 2 different collections (a and b) and they're different, with different fields, currently, there is no way to do so besides running multiple mongo-connector instances, since the "fields" variable is global and not per namespace.

I suggest a different format:

```
"namespaces": {
    "database1.collection1": {
           "fields": [ .... ],
           "target": "database1.dest1",
           .....
    }
}
```

WDIT?

**Comment by ShaneHarvey** [comment]
This sounds like a reasonable feature request. We've added it to the [milestone for 2.5.0.](https://github.com/mongodb-labs/mongo-connector/milestone/6). Thanks!

**Comment by gairom** [comment]
I have the same need.
+1

**Comment by ShaneHarvey** [comment]
Including and excluding fields per namespace was added in #612. The new `namespaces` configuration format is described in the pull request. The [Wiki page|https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces] will be updated with full information soon.
