### ISSUE TITLE
dump_collection is skipped when no docs for namespace exist in oplog.

### ISSUE THREAD

**Issue by estobbart** [mongodb-labs/mongo-connector#498]
I have a MongoDB; I loaded the docs using mongo restore, then turned on replication. So my oplog is empty, but my collections exist.
When the connector is init'd it [checks the timestamp of the file](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L667-L680) which doesn't exist, then [checks the last timestamp of the oplog for my specified namespaces](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L470-L479). But because this doesn't exist either, no dump occurs. Is it possible to have an [alternative path to this piece](https://github.com/mongodb-labs/mongo-connector/blob/master/mongo_connector/oplog_manager.py#L477-L480)? I'm happy to fix it.

**Comment by ShaneHarvey** [comment]
Hi @estobbart,

The fix for this bug (2b48c95) is included in the 2.4.1 release of mongo-connector. If you are still facing problems after upgrading please open a new issue.

Thanks!

**Comment by vimuston** [comment]
The result of this is that now the functionality of mongo-connector is dependant on Python being able to parse all documents in the oplog, even those of other databases and collections. I don't think it's good that the functionality of our application is now dependant on the integrity of data of **other applications** using the same database.
