### ISSUE TITLE
Question: Updating solr index periodically

### ISSUE THREAD

**Issue by prasadh13** [mongodb-labs/mongo-connector#499]
I have a mongodb collection which is indexed in solr. RIght now it updates the index on every insert and update. Is there a way where I can update the solr index say periodically instead?

**Comment by llvtt** [comment]
You can change the rate at which mongo-connector commits to the index by adjusting the [`autoCommitInterval`](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#docmanagersindexautocommitinterval) option.
