### ISSUE TITLE
get an error of rollback in oplog_manager.py

### ISSUE THREAD

**Issue by thakerng** [mongodb-labs/mongo-connector#502]
using mongo-connector 2.4 elastic2_doc_manager 0.1.0

Run
```
mongo-connector --auto-commit-interval=5 -m ${MONGO}:27017 -t ${ES} -v -d elasti
c2_doc_manager --stdout
```

Loggin
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/threading.py", line 901, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.3/site-packages/mongo_connector/util.py", line 90
, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.3/site-packages/mongo_connector/oplog_manager.py"
, line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/local/lib/python3.3/site-packages/mongo_connector/oplog_manager.py"
, line 702, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/local/lib/python3.3/site-packages/mongo_connector/oplog_manager.py"
, line 841, in rollback
    database, coll = original_namespace.split('.', 1)
ValueError: need more than 1 value to unpack
```

**Comment by llvtt** [comment]
Thanks for filing this, @thakerng.

This is very strange. `original_namespace` is supposed to be a string like "database.collection", but apparently it wasn't in that format. What version of MongoDB are you using? Did this happen right when the connector started up? If you're up to it, could you catch this ValueError and log the value of `original_namespace`?

**Comment by thakerng** [comment]
I use mongo:3.3 with elasticsearch:2.2.1 on Rancher's stack ,it happen every time when the connector started up, very first time the existed data in mongodb was synced to Elasticsearch but an error still happen ,next time it doesn't work anymore. The collection of my work is `listings.listings` I log the value of `original_namespace` it display only the name without separated by dot `listings`

**Comment by llvtt** [comment]
Thanks for the additional info! We'll investigate this further.

**Comment by thakerng** [comment]
I work around by degrading MongoDB to 3.2, it's work.

**Comment by ShaneHarvey** [comment]
Hi @thakerng, the 0.1.0 release of the elastic and elastic2-doc-managers contained a bug that may have been causing this issue. Can you try upgrading to the newest release (0.2.0)?
