### ISSUE TITLE
How to exclude field in config.json?

### ISSUE THREAD

**Issue by chientranthien** [mongodb-labs/mongo-connector#504]
i'm able to exclude field by using `-e` command. But it's quite inconvenient
There is any way to put this setting in config.json?

**Comment by llvtt** [comment]
It was omitted from the configuration options page. I just added it here: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#exclude_fields.

You should be able to use `exclude_fields` in your config.json.
