### ISSUE TITLE
connecting

### ISSUE THREAD

**Issue by nikhar03** [mongodb-labs/mongo-connector#508]
Hi,

I am connecting MongoDB and Elastic Search using mongo-connector.
MongoDB is secured with username,password and authentication database.
authentication database is other than admin database.

Where can I specify the authentication database in mongoconnector command?
Please help.

Thanks,
Nikhar Batra

**Comment by ShaneHarvey** [comment]
Hi @nikhar03,

[MongoDB connection strings](https://docs.mongodb.com/manual/reference/connection-string/) support including an authentication database. You can pass these to the -m option of Mongo Connector. For example with user "bar", password "letmein", on database "foodb" you would start Mongo Connector with:

```
$ mongo-connector -m mongodb://bar:letmein@localhost:27017/?authSource=foodb
```

For more information see our [Usage with Authentication](https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20Authentication#using-other-authentication-mechanisms) wiki page.

**Comment by ShaneHarvey** [comment]
If using `authSource` in the connection string doesn't solve this for you or you've got any other questions don't hesitate to open a new issue.
