### ISSUE TITLE
why mongo-connector cannot stay synchronous ? 

### ISSUE THREAD

**Issue by merryjanejian** [mongodb-labs/mongo-connector#511]
mongo oplog has two  shards,and one shard is sync to the destination mongo ,but another shard is not.
what's strange is there is no errors or warnings in log witten by the connector.

**Comment by ShaneHarvey** [comment]
Hi @merryjanejian,

To help us diagnose the problem can you provide some more information about your setup? 

1. What version of Python are you using?
2. What version of `mongo-connector` are you using?
3. Can you post the command line used to start `mongo-connector` including the config file (be sure to redact any sensitive information, eg passwords)?
4. You said there are no errors in the `mongo-connector` log. Are there errors in the `mongod` log files?

When you say the second shard is not in sync, you mean that changes on shard1 on the source are replicated normally but changes on shard2 are not?

**Comment by merryjanejian** [comment]
hi @ShaneHarvey 
1. we use version 2.7 of python
2. we use version 2.3 of  mongo-connector
3.command line:
/usr/bin/python2.7 /usr/bin/mongo-connector -v --stdout --oplog-ts ts.log  --no-dump -m 'mongodb://10.0.0.30:57017/?readPreference=secondary&readPreferenceTags=use:reporting' -t 10.0.0.200:38017 -n db.col1
-g bda.col1  -d mongo_doc_manager

4. yes there were no errors in both mongo-connetor log and mongod log
   we are  sure that mongod log is complete since we've given some tests on it .
5 yes shard1 is so .but shard2 is not.

tonight we will update connector to version 2.4 
and we will see what will happen.

**Comment by shanghaiyangming** [comment]
this problem is https://github.com/mongodb-labs/mongo-connector/commit/2b48c95cb3c7a118c939040e1781cff0677b5019

because rollback with addtional oplog entries was
misinterpreted as falling off the oplog.

we update mongo-connector to 2.4.1 and watch wheater this problem reappear or not~~

**Comment by ShaneHarvey** [comment]
Thanks for the update, glad to know the problem seems to be fixed in the latest release. I'll leave this issue open for the time being just incase.
