### ISSUE TITLE
How does mongo-connector secure data?

### ISSUE THREAD

**Issue by chientranthien** [mongodb-labs/mongo-connector#513]
I want to use mongo-connector for synchronizing from A database to B database which is different domain.  
Are there any situation that my data is leaked?  
And what protocol  are you using for transferring data?

**Comment by ShaneHarvey** [comment]
The connections that mongo-connector establishes to MongoDB and the target data store are fully configurable. For configuring the MongoDB connection see the [Usage with Authentication](https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20Authentication#using-other-authentication-mechanisms) wiki.

For configuring the target connections modify the [targetUrl](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration%20Options#docmanagersindextargeturl) and [args](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration%20Options#docmanagersindexargs) config file options  for each doc manager.

To better help your specific situation can you post some information about your setup? How is your MongoDB cluster secured? What doc manager do you want to use?

**Comment by behackett** [comment]
You can also use SSL/TLS.

**Comment by chientranthien** [comment]
@ShaneHarvey  
I use mongo_doc_manager and currently i'm using basic authentication for development phase

**Comment by ShaneHarvey** [comment]
MongoDB connection strings support including an authentication credentials. For example with user "foo", password "sourcePass" on the source and user "bar", password "targetPass" on the target you could start Mongo Connector with:

`$ cat myconfig.json`
```json
{
    "mainAddress": "mongodb://foo:sourcePass@localhost:27017",
    "docManagers": [{
         "docManager": "mongo_doc_manager",
         "targetURL": "mongodb://bar:targetPass@localhost:27018"
    }]
}
```
`$ mongo-connector --config-file=myconfig.json`

For more information such as how to use mongo-connector with SSL/TLS see our [Usage with Authentication](https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20Authentication) wiki page.
