### ISSUE TITLE
SSL ConfigurationError when executing from a Docker container

### ISSUE THREAD

**Issue by letsgolesco** [mongodb-labs/mongo-connector#515]
I'm running mongo-connector to sync data from a MongoDB instance (hosted on MongoDB Atlas) to an Elasticsearch instance.

When I run it locally from CLI, it works fine. 

However, when I run it within a Docker container, I get this error from pymongo: 
```ConfigurationError: `ssl_cert_reqs` is not ssl.CERT_NONE and no system CA certificates could be loaded. `ssl_ca_certs` is required.```

The only option I'm passing in right now is a config.json file, which looks like this:
```json
{
  "mainAddress": "mongodb://username:password@shard.1.address:27017,shard.2.address:27017,shard.3.address:27017/database-name?readPreference=primary&ssl=true&replicaSet=replica-set-name&authSource=admin",
  "fields": [ "..." ],
  "namespaces": {
    "include": [
        "database.collection1",
        "database.collection2",
        "database.collection3"
    ]
  },
  "docManagers": [
    {
      "docManager": "elastic_doc_manager",
      "targetURL": "https://username:password@host.address:1234",
      "args": {
        "clientOptions": {
          "timeout": 100
        }
      }
    }
  ]
}
```

Workarounds I tried: 
* Manually set `ssl.sslCertificatePolicy` to `"ignored"` - got the same error.
* Removed the `ssl=true` option from `mainAddress` - got a different error (```ServerSelectionTimeoutError: connection closed,connection closed,connection closed```).

**Comment by behackett** [comment]
If your mongod instance is using a TLS cert signed by a well known certificate authority, you need to install [certifi](https://pypi.python.org/pypi/certifi). If not, you need to pass the path to your ca certificate file using the ssl_ca_certs option. See this documentation for pymongo:

https://api.mongodb.com/python/current/examples/tls.html

**Comment by letsgolesco** [comment]
Thanks @behackett - I upgraded the python version in my container and it solved the issue
