### ISSUE TITLE
write integer in mongodb, got float in ES

### ISSUE THREAD

**Issue by arseneparksina** [mongodb-labs/mongo-connector#518]
guys:

I'm using mongodb 3.2.9/elasticsearch 2.3.5/mongo-connector 2.4.1
Everything is working ok, except an Integer problem:
If I do this in mongodb:
    db.patients.save({"_id":"57cfb351890e30f8aef96751","d":7})
I got this in ES:
    {
      "took" : 1,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 1,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "4s2",
          "_type" : "patients",
          "_id" : "57cfb351890e30f8aef96751",
          "_score" : 1.0,
          "_source" : {
            "d" : 7.0
          }
        } ]
      }
    }

the field d, is changed from 7 to 7.0
any idea why?

Thanks in advance,
Dennis

**Comment by arseneparksina** [comment]
use a python or other client to connect mongo, no this problem

**Comment by behackett** [comment]
This is expected behavior of the mongo shell. You can read why here:

https://docs.mongodb.com/manual/core/shell-types/#numberlong
