### ISSUE TITLE
point a secondary

### ISSUE THREAD

**Issue by arseneparksina** [mongodb-labs/mongo-connector#519]
hi, there,

mongo-connector -m localhost:27017 -t localhost:8200 -d elastic2_doc_manager

I have a replica set: localhost:27018
can mongo-connector use a secondary node? so if primary dies, the secondary can be used without restarting mongo-connector.

thanks in advance
Dennis

**Comment by behackett** [comment]
You can use a MongoDB URI to configure mongo-connector. The URI can include a replicaSet option, which provides the name of the replica set and tells PyMongo to discover the members of the replica set and handle failover.

https://github.com/mongodb-labs/mongo-connector/wiki/Configuration%20Options#mainaddresshttps://docs.mongodb.com/manual/reference/connection-string/
