### ISSUE TITLE
Feature Request: `fields` option should propagate edits to array elements

### ISSUE THREAD

**Issue by letsgolesco** [mongodb-labs/mongo-connector#520]
I'm running Mongo Connector to replicate data from a MongoDB instance to an Elasticsearch instance. 

My config includes a `fields` option because I only want a few of my fields to be propagated, including a few array fields.

Some are arrays of strings, others are arrays of objects (including [geojson](http://geojson.org/) objects).

I've noticed that `$addToSet` and `$pull` updates in MongoDB result in the whole array being updated in Elasticsearch, which is fine.

Some important updates aren't replicated in my setup however, including:
* Overwrites of array elements (e.g. `{ $set: { "array.0": "newValue" } }`)
* Edits to objects within arrays (e.g. `{ $set: { "array.$.field": "newValue" } }`)

My feature request is for updates to array elements to be propagated by Mongo Connector when using the `fields` option.

**Comment by kubage88** [comment]
Yeah!  I have the same problem.

**Comment by letsgolesco** [comment]
I've learned that [the `fields` option cannot span arrays](https://github.com/mongodb-labs/mongo-connector/blob/2.4.1/mongo_connector/connector.py#L664-L665).

I guess I'm making a feature request to support the propagation of updates to array elements.

**Comment by ShaneHarvey** [comment]
@letsgolesco Edits to array elements are replicated. Your use of the ``fields`` option might be causing this issue. 

If you want this to be a feature request, can you edit you title/description to include that you want fields to be able to filter inside arrays?

**Comment by ShaneHarvey** [comment]
Fixed by https://github.com/mongodb-labs/mongo-connector/commit/293e3d45d4def8920e980847e4af8a57382b097a.
