### ISSUE TITLE
How to use mongo-connector in AWS environment 

### ISSUE THREAD

**Issue by sopnopriyo** [mongodb-labs/mongo-connector#525]
Locally in ubuntu desktop environment, I am able to push data to elastic search from MongoDB using mongo-connector using the command bellow :

`mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager`

Where shall I run this command in AWS ? 

Your answer with example will be really appreciated . 
Thanks

**Comment by ShaneHarvey** [comment]
You can run Mongo-connector on the same EC2 instance that runs MongoDB, or Elasticsearch, or even a completely separate instance. Any machine that has network access to MongoDB and Elasticsearch will work for you.

I would prefer to run Mongo-connector where ever MongoDB is to simplify the design of the system, but the right place may depend on your use case.

If MongoDB, Elasticsearch, and Mongo-connector should all be running on the same EC2 instance:
```
mongo-connector -m localhost:27017 -t localhost:9200 -d elastic2_doc_manager
```
will continue to work.

If MongoDB and Mongo-connector runs on one instance and Elasticsearch is running another (say  ``ec2-203-0-113-25.compute-1.amazonaws.com``), then you could launch with:
```
mongo-connector -m localhost:27017 -t ec2-203-0-113-25.compute-1.amazonaws.com:9200 -d elastic2_doc_manager
```

**Comment by sopnopriyo** [comment]
Thank you so much Shane Harvey. This is really informative.
