### ISSUE TITLE
mongo-connector gets stuck on oplog entry of non-relevant collection

### ISSUE THREAD

**Issue by vimuston** [mongodb-labs/mongo-connector#526]
(This issue is essentially the same as #279)
mongo-connector stops processing the oplog with message

InvalidBSON: date value out of range

I found that whenever an oplog entry with a date ISODate("0000-12-30T22:00:00Z") was added, mongo-connector stopped following the oplog. However, this entry is in a completely different db/collection. mongo-connector shouldn't even be processing this collection, since our application namespaces.include does not contain this collection. Shouldn't the oplog query target only the namespaces configured?

**Comment by vimuston** [comment]
My primary problem isn't that Python can't read the date -- this is understandable. The issue is that the functionality of our application is now dependant on what other applications/teams using the same database are storing in there.

**Comment by ShaneHarvey** [comment]
The problem is that mongo-connector *must* read all oplog entries to avoid failing when the oplog checkpoint falls off the end of the oplog, see #544. This would happen in your case if the other team performs many operations while your database stays the same.

So we are not going to go back to the old oplog query. Our options are to suggest everyone to [install the PyMongo C Extensions](http://api.mongodb.com/python/current/installation.html#dependencies-for-installing-c-extensions-on-unix) and/or we can catch the "InvalidBSON: date value out of range" exception and simply skip those oplog entries. Thoughts?

**Comment by vimuston** [comment]
Thank you for replying. The reasoning makes sense, and the workaround seems to fix the InvalidBSON issue for us. Closing this issue.

**Comment by vimuston** [comment]
@ShaneHarvey This issue is still persistent in mongo-connector 2.4.1 with pymongo 2.9.3 with C-extensions built-in. I think pymongo does not utilize the C-extensions correctly in all cases. The correct way to handle this is the way you suggested: catch the InvalidBSON exceptions in the oplog thread and skip those entries.

[invalid_bson_trace.txt](https://github.com/mongodb-labs/mongo-connector/files/548033/invalid_bson_trace.txt)

**Comment by ShaneHarvey** [comment]
Your stack trace shows that the version of PyMongo that MongoConnector is using does not have the C extensions installed. It is using the Python implementation of `decode_all` but if the C extensions were available that function would have been replaced with the C version (https://github.com/mongodb/mongo-python-driver/blob/2.9.3/bson/__init__.py#L594-L595) 

Here's an example of installing mongo-connector with pymongo and the c extensions all inside a virtualenv:

For Debian and Ubuntu
`$ sudo apt-get install build-essential python-dev`
For (RHEL, CentOS, Amazon Linux, Oracle Linux, etc.:
`$ sudo yum install gcc python-devel`

Then:
```
$ virtualenv -p python2.7 test-pymongo-c
$ source test-pymongo-c/bin/activate
$ pip install mongo-connector
$ # check if the C extensions are available:
$ python -c 'import bson; print(bson.has_c())'
True
$ # see which version of PyMongo is installed:
$ pip freeze
mongo-connector==2.4.1
pymongo==3.3.0
pysolr==3.5.0
requests==2.11.1
$ # run mongo-connector as usual..
$ mongo-connector <args>
```

Can you verify that the C extensions are installed and check back if you are still getting these errors?

**Comment by vimuston** [comment]
The issue with that is that the environment I am running in does not have internet access, so installing from repositories/internet is not an option. I prebuilt an .egg of pymongo from source with the C extensions and verified on my development machine that the extensions are installed. The problem was in the testing environment:

```
# python
>>> import pymongo
>>> pymongo.has_c()
False
```
Reason:
```
>>> from pymongo import _cmessage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pymongo/_cmessage.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pymongo/_cmessage.py", line 6, in __bootstrap__
ImportError: /home/tsi/.cache/Python-Eggs/pymongo-2.9.3-py2.6-linux-x86_64.egg-tmp/pymongo/_cmessage.so: failed to map segment from shared object: Operation not permitted
```

After analysis I found out the /home filesystem was mounted with 'noexec' option. Removing this flag makes the library load correctly. mongo-connector now got past the problematic entry and seems to be running fine. Closing this issue for now, thanks for your input!

**Comment by ShaneHarvey** [comment]
Great to hear! I think relying on the C extensions is a better solution than patching MongoConnector to deal with `InvalidBSON: date value out of range` errors.
