### ISSUE TITLE
may i use connector  to copy an exist collection in the same port

### ISSUE THREAD

**Issue by Shawn001** [mongodb-labs/mongo-connector#529]
hi, 

  case as follows:
  i have a shard ,  one collection has  37 million collections.
  but , sharded it  needs a long time to split exsits collections.
  when execute this ,  application won't write or read this collection,
  so i want  create a empty collection,and  shard it, then
  use collector to clone collection and sync from old collection.

  is it accessable?

 thanks.

**Comment by ShaneHarvey** [comment]
Using [mongodump](https://docs.mongodb.com/manual/reference/program/mongodump/) and [mongorestore](https://docs.mongodb.com/manual/reference/program/mongorestore) will likely be a lot faster than mongo-connector to copy a collection within a sharded cluster. If you have any questions about using those tools please post on the [MongoDB-User Google Group](https://groups.google.com/forum/#!forum/mongodb-user).
