### ISSUE TITLE
Auditing feature in window environment

### ISSUE THREAD

**Issue by nprasannaganesh** [mongodb-labs/mongo-connector#530]
I would like to enable auditing feature for mongodb in windows environment. As per mongodb documentation (https://docs.mongodb.com/manual/tutorial/configure-auditing/) we cannot use audit parameters like --auditDestination in windows envrionment. Is there an alternate way to enable auditing in windows.

**Comment by ShaneHarvey** [comment]
The documentation states only ``--auditDestination syslog`` is unavailable on Windows. Other uses of ``--auditDestination`` should work.

I'm closing this as it has nothing to do with mongo-connector. In the future, please post general questions about using MongoDB to the [MongoDB-User Google Group](https://groups.google.com/forum/#!forum/mongodb-user).

**Comment by nprasannaganesh** [comment]
Thank you Shane even i was wondering is it right forum or not. Thank you for the forum link.
