### ISSUE TITLE
Sync ElasticSearch docs into mongoDB

### ISSUE THREAD

**Issue by Bunty-Thakkar** [mongodb-labs/mongo-connector#533]
I have used Mongo-connector to dump data from Mongo to ElasticSearch.

But Can i do vice versa.

That is, if i execute a PUT query in Elastic Search, does that entry get reflected in MongoDatabase ??

Thanks.

**Comment by behackett** [comment]
No. mongo-connector is one way, MongoDB to Elastic.

**Comment by Bunty-Thakkar** [comment]
Thanks @behackett
