### ISSUE TITLE
can't sync local neo4j to remote mongo 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [mongodb-labs/mongo-connector#539]
Hi there, when I try

$ mongo-connector -m mongodb://remote.mongodb -a admin -p password  -t http://localhost:7474/db/data -d neo4j_doc_manager

(Assuming this is the right format for remote connections.

I get the message
## _Logging to mongo-connector.log._
and the connector seems to die out, with no error message. 

So basically I'm trying to sync up my local NEO to the remote MONGO. Both databases are running and I can query the remote mongodb from the shell, no problem. 

Is this a size limitation? If so, how could I pick a specific colleciton(s) to sync up locally? 

Thanks

**Comment by alexDeCastroAtGit** [comment]
P.S. when I connect to mongo via
## $ mongod --replSet myDevReplSet
when I try 
> rs.initiate()
### {
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { replSetInitiate: undefined }",
	"code" : 13
}

Do I have to config the --port arg in mongod? SOS!

**Comment by behackett** [comment]
> So basically I'm trying to sync up my local NEO to the remote MONGO

mongo-connector supports synchronizing MongoDB to neo (though we don't maintain that doc manager), not the other way around.

**Comment by alexDeCastroAtGit** [comment]
I understand that, but I can't sync my remote mongo to my local neo. I saw in the docs how to connect my local mongo to my local neo. But is it possible to sync my remote mongo, to my local neo?

**Comment by behackett** [comment]
> But is it possible to sync my remote mongo, to my local neo?

Sure. mongo-connector doesn't care that one server is "local" and one is "remote". You just have to configure it with the correct host/port for each server.

> "errmsg" : "not authorized on admin to execute command { replSetInitiate: undefined }"

I going to assume you started mongod with --auth, but haven't created an admin user yet. You can read about setting up authentication here:

https://docs.mongodb.com/manual/tutorial/enable-authentication/

If you need help with the neo4j doc manager, please ask the developers of that doc manager:

https://github.com/neo4j-contrib/neo4j_doc_manager

**Comment by alexDeCastroAtGit** [comment]
Thanks
