### ISSUE TITLE
How to make mongo-connector highly available in production

### ISSUE THREAD

**Issue by sopnopriyo** [mongodb-labs/mongo-connector#546]
Mongo-connector might go down due to a lot of issues. If one instance is down other should continue to run , that's the traditional practice. 
So, in case of mongo-connector, how can we ensure high availability ?

Thanks,
Shahin 
Cloud Application developer
Hilti

**Comment by gsvarovsky** [comment]
#275 has some discussion of this topic

**Comment by ShaneHarvey** [comment]
Closing as a duplicate of #275
