### ISSUE TITLE
stuck at "Logging to mongo-connector.log"

### ISSUE THREAD

**Issue by secguy** [mongodb-labs/mongo-connector#550]
I'm new to Elastic Search and mongo.

I'm trying to make the connector work, and following the steps at: https://blog.jixee.me/how-to-use-mongo-connector-with-elasticsearch/

When I type in: mongo-connector -m localhost:27017 -t http://localhost:9200 - -d elastic2_doc_manager -n connectortest.syncthis

It gets stuck in "Logging to mongo-connector.log"

nothing gets written in mongo-connector.log

I'm using mongodb3.2.10, elasticsearch 2.3.5 and ubuntu 16.04

and When I type curl localhost:9200/connectortest/_search/?pretty=1, I get

{

"error" : { "root_cause" : [ { "type" : "index_not_found_exception", "reason" : "no such index", "resource.type" : "index_or_alias", "resource.id" : "connectortest", "index" : "connectortest" } ], "type" : "index_not_found_exception", "reason" : "no such index", "resource.type" : "index_or_alias", "resource.id" : "connectortest", "index" : "connectortest" }, "status" : 404 }

Please let me know what I'm doing wrong.

Since I'm newbie to all this, if you need to to provide something pls type in the command.

Thanks

**Comment by ShaneHarvey** [comment]
Check out #548 because this sounds very similar. My guess is that you have an `oplog.timestamp` file that is incompatible with your current setup. Once you've removed the `oplog.timestamp` file , make sure you are using mongo-connector v2.4.1 and try increasing the logging verbosity `-vvvvv`. Post here with the contents of the log if `connectortest.syncthis` is still not being synced.

**Comment by secguy** [comment]
Thanks for getting back to me: 
When I When I type curl localhost:9200/connectortest/_search/?pretty=1 I get the same thing as before...

Here is what I find in mongo-connector.log (the same thing keeps repeating 

2016-10-12 16:52:01,437 [INFO] mongo_connector.connector:1062 - Beginning Mongo Connector
2016-10-12 16:52:01,437 [WARNING] mongo_connector.connector:116 - MongoConnector: Can't find oplog.timestamp, attempting to create an empty progress log
2016-10-12 16:52:01,440 [INFO] mongo_connector.connector:224 - MongoConnector: Empty oplog progress file.
2016-10-12 16:52:01,443 [INFO] mongo_connector.oplog_manager:92 - OplogThread: Initializing oplog thread
2016-10-12 16:52:01,450 [INFO] mongo_connector.connector:296 - MongoConnector: Starting connection thread MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset=u'rs0')
2016-10-12 16:52:01,450 [DEBUG] mongo_connector.oplog_manager:196 - OplogThread: Run thread started
2016-10-12 16:52:01,450 [DEBUG] mongo_connector.oplog_manager:198 - OplogThread: Getting cursor
2016-10-12 16:52:01,450 [DEBUG] mongo_connector.oplog_manager:796 - OplogThread: reading last checkpoint as None

**Comment by ShaneHarvey** [comment]
Do you have any data in your `connectortest.syncthis` collection? How are you setting up your MongoDB replica set?

**Comment by secguy** [comment]
yes, I got the steps from https://blog.jixee.me/how-to-use-mongo-connector-with-elasticsearch/

**Comment by ShaneHarvey** [comment]
I just followed the steps in the blog and mongo-connector is working correctly. The envirnoment I used:
```
$ pip freeze
elastic2-doc-manager==0.2.0
elasticsearch==2.4.0
mongo-connector==2.4.1
pymongo==3.3.0
pysolr==3.5.0
requests==2.11.1
urllib3==1.18
$ python --version
Python 2.7.10
$ elasticsearch --version
Version: 2.4.1, Build: c67dc32/2016-09-27T18:57:55Z, JVM: 1.8.0_101
```

**Comment by secguy** [comment]
I have the same thing as you. Maybe something is messed up in some config file?

**Comment by ShaneHarvey** [comment]
The continuous `OplogThread: reading last checkpoint as None` is curious. Can you post the results of doing this query on the oplog:
```js
$ mongo
replset:PRIMARY> db.getSiblingDB('local').oplog.rs.find({'op': {'$ne': 'n'}})
{ "ts" : Timestamp(1476383223, 1), "t" : NumberLong(1), "h" : NumberLong("-2162862907642869777"), "v" : 2, "op" : "c", "ns" : "test.$cmd", "o" : { "create" : "syncthis" } }
{ "ts" : Timestamp(1476383231, 1), "t" : NumberLong(1), "h" : NumberLong("7304239807159334729"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00e9"), "value" : 1 } }
{ "ts" : Timestamp(1476383231, 2), "t" : NumberLong(1), "h" : NumberLong("-8248491923735036564"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00ea"), "value" : 2 } }
{ "ts" : Timestamp(1476383231, 3), "t" : NumberLong(1), "h" : NumberLong("-5605438027938883713"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00eb"), "value" : 3 } }
{ "ts" : Timestamp(1476383231, 4), "t" : NumberLong(1), "h" : NumberLong("5246647303464579780"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00ec"), "value" : 4 } }
{ "ts" : Timestamp(1476383231, 5), "t" : NumberLong(1), "h" : NumberLong("-6253657029195632346"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00ed"), "value" : 5 } }
{ "ts" : Timestamp(1476383231, 6), "t" : NumberLong(1), "h" : NumberLong("-8791675141164850653"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00ee"), "value" : 6 } }
{ "ts" : Timestamp(1476383231, 7), "t" : NumberLong(1), "h" : NumberLong("826405003525462257"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00ef"), "value" : 7 } }
{ "ts" : Timestamp(1476383231, 8), "t" : NumberLong(1), "h" : NumberLong("-8378934537628512896"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00f0"), "value" : 8 } }
{ "ts" : Timestamp(1476383231, 9), "t" : NumberLong(1), "h" : NumberLong("-3714880016068678879"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00f1"), "value" : 9 } }
{ "ts" : Timestamp(1476383231, 10), "t" : NumberLong(1), "h" : NumberLong("-8597394414313570996"), "v" : 2, "op" : "i", "ns" : "test.syncthis", "o" : { "_id" : ObjectId("57ffd1ff1beca117adaa00f2"), "value" : 10 } }
```

**Comment by secguy** [comment]
hmm there is some syntax error : 


2016-10-14T21:32:29.732-0400 E QUERY    [thread1] SyntaxError: missing ; before statement @(shell):1:7

**Comment by ShaneHarvey** [comment]
Are you running `db.getSiblingDB('local').oplog.rs.find({'op': {'$ne': 'n'}});` in the MongoDB shell?

**Comment by ShaneHarvey** [comment]
@secguy are you still having issues?

**Comment by secguy** [comment]
Hi Shane,

Thanks so much for your help. yes. I still had issues. but I gave up on this piece. I will do things differently.

I will close this ticket.
