### ISSUE TITLE
how to restart mongo-connector in linux ?

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb-labs/mongo-connector#558]
i have installed mongo-connector with this command  pip install mongo-connector now i wan to restart mongo-connector please help me

**Comment by vimuston** [comment]
As far as I know, you can just kill the process.

**Comment by ShaneHarvey** [comment]
@vimuston is correct. Ctrl-C or `kill -SIGINT`:

```
$ mongo-connector <args>
Logging to mongo-connector.log.
^C
$ mongo-connector <args>
Logging to mongo-connector.log.
```
