### ISSUE TITLE
Deprecated groovy script in Elasticsearch 5.0.0

### ISSUE THREAD

**Issue by plusbpm** [mongodb-labs/mongo-connector#571]
I get warnings when using the connector with Elasticserch 5.0.0:

```
[WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
```

**Comment by ShaneHarvey** [comment]
I can't reproduce this and the elastic2-doc-manager does not enable or use scripts. Perhaps your Elasticsearch configuration has groovy scripts enabled?

**Comment by plusbpm** [comment]
Unfortunately I do not know, use a clean installation of elasticsearch5.0.0 
I will check it.

**Comment by ShaneHarvey** [comment]
A clean installation of Elastic 5.0.0 prints this message to log. This is part of Elastisearch's plan to remove many scripting languages and has nothing to do with mongo-connector, see https://github.com/elastic/elasticsearch/issues/20129.

**Comment by mostolog** [comment]
This warning still appears running elasticsearch 5.2.1. 

[WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead

will it disappear upon scripts folder deletion? Is there any way not to print this message?

**Comment by ShaneHarvey** [comment]
@mostolog I suggest you disable scripting according to https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html.

**Comment by mostolog** [comment]
@ShaneHarvey 
Using the following lines on my elasticsearch.yml config didn't make that warning go away...ideas?
```
script.inline: false 
script.stored: false 
script.file:   false 
script.engine.groovy.inline: false 
script.engine.groovy.stored: false
script.engine.groovy.file: false
```

**Comment by ShaneHarvey** [comment]
I got nothing. Can you open an issue on https://github.com/elastic/elasticsearch/?
