### ISSUE TITLE
Lots of permissions failures.

### ISSUE THREAD

**Issue by fuqqer** [mongodb-labs/mongo-connector#584]
I have a mongo 3.0 sharded replica set MONGOFOO.  I have a new mongo 3.2 replica set MONGOBAR.

I created a user mongosuper with clustermanager, clusteradmin, adminanydatabase, readwriteanydatabase, and useradminanydatabase on both clusters.  

I installed mongo connector on a mongorouter for MONGOFOO. I copied my mongouser's password into a passwordfile on the router.

I run:
mongo-connector -v -m localhost:27107 -t MONGOBARprimary.mydomain.com:27017 -d mongo_doc_manager --admin-username mongosuper --password-file passwordfile  

The process fails with tracebacks saying stuff like this:
OperationFailed: not authorized on __mongo_connector to execute command { update: "tap.checkpoints", updates: [ { q: { _id: "blah.mydomain.com", ns: "taap.message_metadata_consumer_checkpoints" }, u: { _id: "blah.mydomain.com", ns: "tap.checkpoints", _ts: 6350740472968773640 }, multi: false, upsert: true } ] }

I verified that the username/password is correct and I can list collections in all DBs on both replica sets.

How do I get mongo-connector working between a sharded replica set and a regular replica set?

**Comment by ShaneHarvey** [comment]
You have specified the credentials for connecting to the **source** MongoDB cluster but you need to also specify the credentials for the **target** MongoDB replica set. You can do this with a [connection URI](https://docs.mongodb.com/manual/reference/connection-string/). To prevent your password ending up on the command line, you should use a config file: 
```json
{
  "mainAddress": "mongodb://mongoSourceUser:password@localhost:27107",
  "verbosity": 1,
  "docManagers": [
    {
      "docManager": "mongo_doc_manager",
      "targetURL": "mongodb://mongoTargetUser:password@MONGOBARprimary.mydomain.com:27017/?replicaSet=myReplSetName"
    }
  ]
}
```
