### ISSUE TITLE
GridFS collections not replicating.

### ISSUE THREAD

**Issue by fuqqer** [mongodb-labs/mongo-connector#590]
I'm running mongo-connector between 3.0 and 3.2.  I have a couple gridfs collections in my 3.0 sharded cluster and they are not replicating into my 3.2 replica set.  I am running mongo-connector without specifying a namespace, so I would assume it should be grabbing all namespaces including gridfs.

**Comment by ShaneHarvey** [comment]
Mongo-connector does not replicate gridfs collections by default. You must use the [gridfs configuration option](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#namespacesgridfs) to specify which gridfs collections to sync.
