### ISSUE TITLE
Replace with Kafka connector  

### ISSUE THREAD

**Issue by liu0013** [mongodb-labs/mongo-connector#594]
make mongo source kafka connector + elasticsearch sink kafka connector to replace current implementation?

**Comment by ShaneHarvey** [comment]
I'm not entirely sure what you're asking.

**Comment by liu0013** [comment]
I just want to say the other solution which is based on kafka. make a source kafka connector to put pslog into kafka and make a sink kafka connector to consume pslog event from kafka then insert/update/ into elaticsearch/other storage.     
Please refer to 
https://www.confluent.io/product/connectors/
http://debezium.io/docs/connectors/mongodb/
https://github.com/confluentinc/kafka-connect-elasticsearch

**Comment by liu0013** [comment]
I just want to say the other solution which is based on kafka. make a source kafka connector to put pslog into kafka and make a sink kafka connector to consume pslog event from kafka then insert/update/ into elaticsearch/other storage.     
Please refer to 
https://www.confluent.io/product/connectors/
http://debezium.io/docs/connectors/mongodb/
https://github.com/confluentinc/kafka-connect-elasticsearch

**Comment by ShaneHarvey** [comment]
Yes, it sounds like it's possible to connect MongoDB to Elasticsearch via the Kafka MongoDB (Source) connector and Kafka Elasticsearch (Sink) connector.
