### ISSUE TITLE
Mongo-connector in Docker and role of oplog.timestamp and mongodb_meta ?

### ISSUE THREAD

**Issue by marknorkin** [mongodb-labs/mongo-connector#596]
I'm running a mongo-connector as one of containers using docker-compose. I'm replicating data to ElasticSearch. I'm using options like `restart: always` in compose. Also when container starts I wrote a small python script that drops es index (if exists) and creates fresh one, so I can be sure that all of data I need were in ElasticSearch.

I'm wondered about the case when container fails (for example due to reaching memory limits) and then restarts again. Do i need in those cases to recreate index or not ? At this time I'm not clear about the role of `oplog.timestamp` and `mongodb_meta` es index that connector creates and how they relate ? Should I put `oplog.timestamp` in volume ? If I drop my index, should I also drop `mongodb_meta` ?

**Comment by ShaneHarvey** [comment]
The `oplog.timestamp` file saves the MongoDB operation that mongo-connector should restart so it shoul be saved and restored between Docker restarts. See  the [Oplog Progress File overview](https://github.com/mongodb-labs/mongo-connector/wiki/Oplog-Progress-File) for more information.

You should not need to delete any indexes (especially `mongo_meta`) in Elasticsearch unless you want to [resync the connector](https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing-the-Connector).

**Comment by marknorkin** [comment]
So in order to do full re-sync I need to: 

1. stop container 
2. delete `oplog.timestamp` file
3. drop my domain index in ElasticSearch
4. drop  `mongodb_meta` in ElasticSearch
5. bring container back up

Is that right ?

**Comment by ShaneHarvey** [comment]
That's correct.

**Comment by marknorkin** [comment]
Great!

So I have another question that is interesting for me. I looked through the docs and find that [multiple instances can be run simultaneously](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#can-i-run-more-than-one-instance-of-mongo-connector-at-the-same-time), so when I:
1. run multiple `mongo-connector` instances, each in a separate docker container
2. and each instance used to replicate data from configured mongo collections to separate ElasticSearch index

Every instance has it's own `oplog.timestamp` file, but they all share the `mongodb_meta` index in ElasticSearch ?

So when the re-sync needed for one of the instances, to do it properly you should not drop the whole `mongodb_meta` index, but delete only documents with specific namespace in that index ?
