### ISSUE TITLE
Java based mongo-connector ?

### ISSUE THREAD

**Issue by ashishgaikwad** [mongodb-labs/mongo-connector#598]
In there any option or plan for Java based mongo connector. I have often come across secured environments where Python is not available but Java is. This is often due to lots of enterprise financial applications being in Java.

**Comment by behackett** [comment]
I'm curious what environments you're thinking of. All Linux systems that I've seen have a system python available. None of them, that I know of, come with a system Java. The only thing you need other than a python interpreter is the PyMongo package, which by default has no dependencies of its own.

**Comment by ashishgaikwad** [comment]
Thanks for the quick response @behackett and explaining the system Python availability. Since I am not so familiar with Linux. However in my current and previous organisations (both banks) I have seen pretty stripped down versions of Linux with required only software. Java is made available since often the app servers are in Java. Also these servers are patched by infra team and do not have Internet connectivity :(

**Comment by behackett** [comment]
The reason I mention system availability for python is that package managers on many (most?) Linux systems are written in python. That is, you can't install system packages on most Linux distros without having python.

I understand the problem that not all systems have internet connectivity, but if your going to install mongo-connector without internet connectivity, it's no more difficult to install its one required dependency, PyMongo, without internet connectivity.

**Comment by behackett** [comment]
I'm going to close this ticket as re-writing mongo-connector in Java would be a serious undertaking we won't do without a really compelling reason, or anytime soon.
