### ISSUE TITLE
namespaces.include does not support wildcards like 'a.c.*'

### ISSUE THREAD

**Issue by aietcn** [mongodb-labs/mongo-connector#599]
Hi, I just started using mongo-connector. I find that mongo-connector configurations (namespaces.include) does not support wildcards for collection names like 'a.c.1'. (currently using mongo-connector 2.4.1, installed with pip)

I want to sync data between A: `localhost:27017` (the cluster) and B: `localhost:28018` (the target).

A contains database `a`, in which contains collections `test`, `c.1` and `c.2`. I started A as a single replica set and B as an independent instance. Then start mongo-connector with configuration below.

```
{
  "mainAddress": "localhost:27017",
  "namespaces": {
    "include": ["a.c.*"]
  },
  "docManagers": [{
    "docManager": "mongo_doc_manager",
    "targetURL": "localhost:28018"
  }]
}
```

When I insert data into A: `a.c.1`, no data gets synced into B. But when I change `namespace.include` to `["a.c.1"]` in the config file, everything charmingly works.

------

I just tested with wildcards like `a.b_*` and `a.b*`, not working either. Is this a bug?

**Comment by BlueRayONE** [comment]
This feature is already implemented and will be released soon.
See #495.

**Comment by aietcn** [comment]
@BlueRayONE great to hear that. Since this feature is already documented in the [wiki](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces) and [examples](https://github.com/mongodb-labs/mongo-connector/blob/master/config.json), I thought it has already been released in the latest version.

**Comment by ShaneHarvey** [comment]
I verified that this is working correctly in mongo-connector 2.5.0. Please update to the latest version and check out the [CHANGELOG for 2.5.0](https://github.com/mongodb-labs/mongo-connector/blob/2.5.0/CHANGELOG.rst#version-250).
