### ISSUE TITLE
Namespace wildcard parsing is matching unwanted collections

### ISSUE THREAD

**Issue by letsgolesco** [mongodb-labs/mongo-connector#600]
### Background

My MongoDB has multiple databases with the same set of collections.

I'm using wildcards in the `namespaces.include` config option to transport the same collections from multiple databases, like so:
```json
  "namespaces": {
    "include": [
      "*.accounts"
    ]
  }
```

There is a collection called `accounts`, which I want to transport to Elasticsearch.

There is a collection called `deletedaccounts`, which I **do not** want to transport to Elasticsearch.

### Problem

Mongo Connector is transporting documents from the `deletedaccounts` MongoDB collection to Elasticsearch, creating a new Elasticsearch type called `delete.accounts`.

I found [this line in the dest_mapping.py file](https://github.com/mongodb-labs/mongo-connector/blob/293e3d45d4def8920e980847e4af8a57382b097a/mongo_connector/dest_mapping.py#L79) and it turns my `"*.accounts"` into the regex `/(.*).accounts/` which matches both `database.accounts` and `database.deletedaccounts`.

### Possible solution

A possible solution here is to escape regex characters in namespace strings (except for the `*` wildcard that we want to use in the regex). 

In my case, `/(.*).accounts/` would become `/(.*)\.accounts/`. 

I'm not sure if this solution would negatively effect other components.

**Comment by ShaneHarvey** [comment]
Thanks for finding this bug! It should be fixed in https://github.com/mongodb-labs/mongo-connector/pull/601 by escaping special characters in the namespace, like "." and "$", before creating a regex like you suggested.

**Comment by letsgolesco** [comment]
Thanks for getting on this quickly!
