### ISSUE TITLE
mongo_connector errors InvalidConfiguration  Could not import mongo_connector.doc_managers.elastic2_doc_manger.

### ISSUE THREAD

**Issue by DBARUNNER** [mongodb-labs/mongo-connector#602]
I have installed elastic2_doc_manger with pip and also mongo connector  in non root user 
when i run this command 
$ mongo-connector -m 10.20.1.123:27017 -t 10.20.1.123:9200 -d elastic2_doc_manger 
i recieve this error 
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2_doc_manger. It could be that this doc manager has been moved out of this project and is maintained elsewhere. 
Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers

I want to use it with elasticsearch 5.0.1

**Comment by BlueRayONE** [comment]
As you can see in the name, "elastic2_doc_manager" is only for ElasticSearch 2.x. 
Version 5 of ES is not supported yet, a new doc manager is needed. So you can't use the connector with your setup atm. @ShaneHarvey should know if and for when elastic5_doc_manager is planned.

**Comment by ShaneHarvey** [comment]
@DBARUNNER it looks like you misspelled the `elastic2_doc_manager` as `elastic2_doc_manger`.

Also, we just released mongo-connector 2.5.0 and elastic2-doc-manager 0.3.0 with support for Elasticsearch 5.x. To upgrade mongo-connector and use the elastic2-doc-manager with Elasticsearch 5x:
`pip install --upgrade 'mongo-connector[elastic5]'`
