### ISSUE TITLE
-n/-x database.collection does not work

### ISSUE THREAD

**Issue by bakhshandeh** [mongodb-labs/mongo-connector#617]
I have a mongodb database including 2 collections and want to connect it to ElasticSearch 5.x. Everything is working without -x/-n options. But when I want to include/exclude one of collections, mongo-connector does not create any indexes in ES.

This is working:
mongo-connector -m localhost:27017 -t http://localhost:9200 -d elastic2_doc_manager

These are not working:
mongo-connector -m localhost:27017 -t http://localhost:9200 -n test_db.test -d elastic2_doc_manager
mongo-connector -m localhost:27017 -t http://localhost:9200 -x test_db.test_new -d elastic2_doc_manager

MongoDB 3.2.9
Python 2.7.6
Ubuntu 14.04.4 LTS
ElasticSearch 5.1.1

**Comment by ShaneHarvey** [comment]
I can't reproduce this with mongo-connector 2.5.0. What version are you using? If you're still experiencing this issue, running mongo-connector with `--verbose` may uncover the problem.

**Comment by bakhshandeh** [comment]
My mistake :).
Just forgot to delete oplog.timestamp. Its working now.

**Comment by ShaneHarvey** [comment]
Thanks for the update, glad it's working :)
