### ISSUE TITLE
MongoDB custom filter

### ISSUE THREAD

**Issue by Apoorva333** [mongodb-labs/mongo-connector#618]
I am using mongo connector to map data from mongodb to elasticsearch. Is there any property available in the mongo-connector through which I would be able to index a collection(for the very first time) consisting of documents of only a particular date range(which can be identified by "date" field in each document) from mongodb ?

mongo-connector version: 2.5.0.dev0
Source MongoDB version: 3.0.12
Elasticsearch version: 1.4.4

**Comment by ShaneHarvey** [comment]
Closing as duplicate of https://github.com/mongodb-labs/mongo-connector/issues/304.
