### ISSUE TITLE
Is there any way to change field names in Mongo documents?

### ISSUE THREAD

**Issue by malekascha** [mongodb-labs/mongo-connector#622]
I am using Mongo connector with elasticsearch. I'm currently trying to add a collection but it fails to add because one of the field names on the documents is _type, which is reserved in Elasticsearch, causing an error to be thrown. Is there any way for me to configure mongo connector to use a different name for that field when indexing the documents? I know there's a way to store the collection under a different name, but I can't find a way to change document field names.

**Comment by ShaneHarvey** [comment]
There's no way to change field names but in mongo-connector 2.5.0 you can exclude the problematic `"type"` field by [filtering fields on a collection](https://github.com/mongodb-labs/mongo-connector/pull/612) via the "namespaces" configuration option. The following config will cause mongo-connector to include only collections in the `my_db` database and exclude the  `"_type"` field from all documents.
```json
{
    "other options...":"",
    "namespaces": {
        "my_db.*": {
            "excludeFields": ["_type"]
        },
    },
}
```

With this config a document such as `{"_type": "my_type", "foo": "bar"}` will be replicated  without "_type": `{"foo": "bar"}`

**Comment by malekascha** [comment]
Thank you very much Shane, this worked perfectly. I recommend that the new way of setting up namespaces displayed in the pull request you linked to get added to the configuration options section of the wiki. It still has the old way of doing things on there.
