### ISSUE TITLE
mongo-connector may attempt to log a warning before the logging module is setup

### ISSUE THREAD

**Issue by Aditya-Sh** [mongodb-labs/mongo-connector#623]
Can anybody help me with this? What does this below statement means?
`No handler could be found for logger "mongo_connector.connector"`

**Comment by BlueRayONE** [comment]
Take a look into the [existing issues](https://github.com/mongodb-labs/mongo-connector/search?utf8=%E2%9C%93&q=No+handler+could+be+found+for+logger&type=Issues) to this topic and check the solutions described there. Perhaps there is a solution for your problem. How did you write the doc-manager name?

Some additional information to your setup like connector version and used doc-manager would be useful.

**Comment by Aditya-Sh** [comment]
elasticsearch (5.0.1)
mongo-connector (2.5.0)
elastic2-doc-manager (0.3.0)

I am using config.json for all configuration, my doc manager array is as below:
`"docManagers": [
        {
            "docManager": "elastic2_doc_manager",
            "targetURL": "http://192.168.1.52:9200",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]`

**Comment by ShaneHarvey** [comment]
Thanks for finding this issue! The problem is that we try to [log a deprecation warning](https://github.com/mongodb-labs/mongo-connector/blob/2.5.0/mongo_connector/connector.py#L808) for old-style namespaces configuration before logging has been setup. The fact that the warning does not appear is a bug introduced in https://github.com/mongodb-labs/mongo-connector/pull/612.

**Comment by Aditya-Sh** [comment]
Can you help me with new new namespaces configuration? I documentation is in for old versions and example config is for new version.
In old versions for including namespaces:
`"include" : ["db_name.collection1", "db_name.collection2", "db_name.collection3"]`

But sample file has something like: 
`"included.collection4": {
            "includeFields": ["included_field", "included.nested.field"]
 },`

Can you give a explain the above format, also how renaming works in new versions?

**Comment by rectalogic** [comment]
Your old version
`"include" : ["db_name.collection1", "db_name.collection2", "db_name.collection3"]`
would look like:
`"namespaces": {"db_name.collection1"; true, "db_name.collection2": true, "db_name.collection3": true}`
Rename by specifying an object value for the namespace, e.g. the above with renaming `db_name.collection1`:
`"namespaces": {"db_name.collection1": {"rename": "db_name.new_collection1"}, "db_name.collection2": true, "db_name.collection3": true}`

**Comment by ShaneHarvey** [comment]
I've updated the `namespaces` wiki page for the 2.5.0 release: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces

**Comment by Aditya-Sh** [comment]
@rectalogic and @ShaneHarvey 
Thank you for help.
