### ISSUE TITLE
Way to index existing data

### ISSUE THREAD

**Issue by Aditya-Sh** [mongodb-labs/mongo-connector#624]
Is there a way I can index already existing data in my database?

**Comment by BlueRayONE** [comment]
If this is not done on initial start-up of the connector (not sure yet), you can definitly archive this by [doing a resync](https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing-the-Connector#how-to-perform-a-re-sync). Shutdown the connector, delete the oplog-timestamp and restart the connector.

**Comment by ShaneHarvey** [comment]
If you are talking about [MongoDB indexes](https://docs.mongodb.com/manual/indexes/), mongo-connector does not copy or create any indexes. You'll have to create indexes manually.

**Comment by Aditya-Sh** [comment]
I meant elasticsearch index. I already have lot of data in my mongodb, I wanted to push these data to elasticsearch. Since mongo-connector uses oplog, it is not sending already existing data to elastic.

**Comment by ShaneHarvey** [comment]
mongo-connector is supposed to copy existing data the first time it is run unless the oplog progress file already exists or the [`noDump`](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#nodump) option is set. The [oplog progress file](https://github.com/mongodb-labs/mongo-connector/wiki/Oplog-Progress-File) wiki page contains more a detailed explanation of this behavior.

The fact that existing data was not copied means there is probably a configuration problem. Make sure the `noDump` option is not set and try [resyncing the connector](https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing-the-Connector). If the problem persists, post back here with your environment, mongo-connector log, and mongo-connector config. Be sure to remove any sensitive information before you post.

**Comment by Aditya-Sh** [comment]
Hello, Thanks for the help, above solution works. 
Small data collections get indexed easily (one with around 100-150 items).
I am only having problem with large datasets (around 4000-5000 items), still investigating that. Will get back to you on that.

**Comment by ShaneHarvey** [comment]
If you are still having issues syncing documents please open a new issue with detailed steps to reproduce the problem.

**Comment by anuj2024** [comment]
mongo-connector fetches the data for previously created indexes only, whenever new index gets created it throws an error and doesn't pull any records?
