### ISSUE TITLE
Config.json file is not the latest

### ISSUE THREAD

**Issue by nijeshku1992** [mongodb-labs/mongo-connector#625]
The examples given for namespaces in the config.json is not as per the latest code.

**Comment by ShaneHarvey** [comment]
What exactly is the problem in the current `config.json` file?

**Comment by ShaneHarvey** [comment]
If you're referring to the Configuration File options wiki page, I've just updated the namespaces section for 2.5.0: https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#configure-namespaces

**Comment by nijeshku1992** [comment]
Thanks for correcting the wiki file. This was creating confusion and also the new configuration is not working for me. I switched back to the old configuration style for namespaces and am using the version 2.5.0

In this code snippet, what does "collection1" stands for is it dbName.collectionName or just collectionName?
`{
  "namespaces": {
    "included.collection1": true,
    "included.collection2": {},
    "included_wildcard.*": true
  }
}`

**Comment by nijeshku1992** [comment]
In this code snippet, what does "collection1" stands for is it dbName.collectionName or just collectionName? This is not correctly mentioned in the wiki
`{
  "namespaces": {
    "included.collection1": true,
    "included.collection2": {},
    "included_wildcard.*": true
  }
}`

**Comment by ShaneHarvey** [comment]
From the wiki: "Namespaces should be given as `database_name.collection_name`"

That means "included.collection1" references the "collection1" collection in the "included" database.

**Comment by nijeshku1992** [comment]
What is "included" database? How to include a database using config.json? This is not mentioned in the doc. 
For Eg:
 `    "namespaces":{
        "included.sparks":true
    }`
With this configuration "sparks" collection is not getting replicated

**Comment by ShaneHarvey** [comment]
If the "sparks" collection is in a database named "test_database" then your config file should look like:
```json
{
  "namespaces": {
    "test_database.sparks":true
  }
}
```

**Comment by nijeshku1992** [comment]
Thanks again for your help. This information is not properly conveyed in the document. It will be really helpful If you could replace the term "included" with "included_db".
Should i close the issue?

**Comment by ShaneHarvey** [comment]
Thanks for pointing that out, I added  'db' or 'database' to the database names.
