### ISSUE TITLE
pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1 }

### ISSUE THREAD

**Issue by ballerabdude** [mongodb-labs/mongo-connector#626]
Why do I keep getting the error below
`pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1 } `

`

my config json is below
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "mongodb://cluster-a0.mlab.com:35828,cluster-a1.mlab.com:35828/admin?replicaSet=rs-cluster",
    "oplogFile": "/var/log/mongo-connector/oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 3,
    "continueOnError": false,

    "logging": {
        "type": "stream",
        "__filename": "/var/log/mongo-connector/mongo-connector.log",
        "__format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,

        "__type": "syslog",
        "__host": "localhost:514"
    },

    "authentication": {
        "adminUsername": "oplog-reader",
        "password": "password",
        "__passwordFile": "mongo-connector.pwd"
    },

    "__comment__": "For more information about SSL with MongoDB, please see http://docs.mongodb.org/manual/tutorial/configure-ssl-clients/",
    "__ssl": {
        "__sslCertfile": "Path to certificate to identify the local connection against MongoDB",
        "__sslKeyfile": "Path to the private key for sslCertfile. Not necessary if already included in sslCertfile.",
        "__sslCACerts": "Path to concatenated set of certificate authority certificates to validate the other side of the connection",
        "__sslCertificatePolicy": "Policy for validating SSL certificates provided from the other end of the connection. Possible values are 'required' (require and validate certificates), 'optional' (validate but don't require a certificate), and 'ignored' (ignore certificates)."
    },

    "__fields": ["field1", "field2", "field3"],

    "namespaces": {
        "include": [
            "mydb.jobs",
            "mydb.workflows"
        ]
    },

    "docManagers": [
        {
            "docManager": "solr_doc_manager",
            "targetURL": "http://192.168.99.100:8983/solr/gettingstarted",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]
}

`

**Comment by ShaneHarvey** [comment]
It looks like the `oplog-reader` user does not have the [required permissions](https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Authentication#required-permissions). Please consult that wiki page and make sure your mongo-connector user has a sufficiently privileged role, eg "backup".

**Comment by ballerabdude** [comment]
@ShaneHarvey You maybe right but i don't think there is a way to change that on mlabs

**Comment by ShaneHarvey** [comment]
Can you log in as the "oplog-reader" user then run `connectionStatus` and `listDatabases`?

```
$ mongo
> db.getSiblingDB("admin").auth('mongo-connector-username', 'password');
1
> db.runCommand( { connectionStatus: 1 } )
{
	"authInfo" : {
		"authenticatedUsers" : [
			{
				"user" : "mongo-connector-username",
				"db" : "admin"
			}
		],
		"authenticatedUserRoles" : [
			{
				"role" : "backup",
				"db" : "admin"
			}
		]
	},
	"ok" : 1
}
> db.runCommand( { listDatabases: 1 } )
{
	"databases" : [
		{
			"name" : "admin",
			"sizeOnDisk" : 131072,
			"empty" : false
		},
		{
			"name" : "blog",
			"sizeOnDisk" : 106496,
			"empty" : false
		},
		{
			"name" : "local",
			"sizeOnDisk" : 32768,
			"empty" : false
		}
	],
	"totalSize" : 270336,
	"ok" : 1
}
```

Try creating a new user with the "backup" role:

```
$ mongo
replset:PRIMARY> db.getSiblingDB("admin").createUser(
  {
    user: "mongo-connector-username",
    pwd: "password",
    roles: ["backup"]
  }
)
```
If mlabs does not let you create a new MongoDB user with the backup role, what about `readAnyDatabase` and `read@local`?:
```
$ mongo
replset:PRIMARY> db.getSiblingDB("admin").createUser(
  {
    user: "mongo-connector-username",
    pwd: "password",
    roles: [
       "readAnyDatabase",
       { role: "read", db: "local" },
    ]
  }
)
```

**Comment by ballerabdude** [comment]
@ShaneHarvey Sorry for responding  late but the oplog user is just a read only user. It looks like I may not be able to use mongo-connector with mlab shared databases. I will try to look around to code to see if I can implement a  way to reference a database by name and use  another user to read from that database

**Comment by ShaneHarvey** [comment]
Thanks, let us know if you make any progress with mlabs shared databases. I'm not familiar with their platform but mongo-connector only requires read permissions on the source MongoDB so if you are able to create a new user in the "admin" database you should be good to go. Otherwise, like you said, it won't be possible because we need to read from both the oplog and all the databases you'd like to replicate.

**Comment by ballerabdude** [comment]
@ShaneHarvey I have implemented a way to provide another set of credentials with a db name for a shared environment. When I add the options from the config why do I have set a cli flag? If I dont set it I get an error so I created a flag I am not using to quit the error.
https://github.com/ballerabdude/mongo-connector/blob/4f8b837fc5f169981db6575142699df13906afc9/mongo_connector/connector.py#L482

ps: Everything works fine during my tests and was able to use both credentials.

**Comment by ShaneHarvey** [comment]
@ballerabdude I believe I have fixed this issue and added a test case that ensures mongo-connector can work with a user that does not have the privilege to run the listDatabases command. 

Are you able to install the development version and confirm the fix?
To install:
```
$ pip install https://github.com/mongodb-labs/mongo-connector/archive/master.zip
$ mongo-connector --version
mongo-connector version: 2.5.1.dev0
```

**Comment by ballerabdude** [comment]
Hey @ShaneHarvey I finally had some time to go over the project I was working on and it looks like the oplog user cannot listCollections. I just emailed mlab to ask about the exact role that the oplog user has. Here is the error tho.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/util.py", line 104, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/oplog_manager.py", line 197, in run
    cursor, cursor_empty = retry_until_ok(self.init_cursor)
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/oplog_manager.py", line 739, in init_cursor
    timestamp = self.dump_collection()
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/oplog_manager.py", line 534, in dump_collection
    dump_set, gridfs_dump_set = get_all_ns()
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/oplog_manager.py", line 515, in get_all_ns
    self.primary_client[database].collection_names)
  File "/usr/local/lib/python3.5/dist-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 533, in collection_names
    results = self._list_collections(sock_info, slave_okay)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 505, in _list_collections
    cursor = self._command(sock_info, cmd, slave_okay)["cursor"]
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 406, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on <MY DB> to execute command { listCollections: 1, cursor: {} }
```
