### ISSUE TITLE
sync some skipped files

### ISSUE THREAD

**Issue by anekix** [mongodb-labs/mongo-connector#628]
i am performing a sync from mongo to elastic. my mongoconnector was running perfect .until i added some auth to elastic instance then mongoconnector could not put some data in elastic( which is expected, as it has to authenticate first) . later i added auth to mongoconnector. now new inserts in mongo are getting replicated but the older ones are not getting synced to elastic. how do i make them resyn?

**Comment by ShaneHarvey** [comment]
You will have to perform a resync to get the skipped documents/updates into Elasticsearch. Check out the wiki page for [resyncing mongo-connector](https://github.com/mongodb-labs/mongo-connector/wiki/Resyncing-the-Connector).
