### ISSUE TITLE
Mongo-connector shutting down after collections dump 

### ISSUE THREAD

**Issue by Webgardener** [mongodb-labs/mongo-connector#634]
Hi. 

I use mongo-connector to perform a synchronization between 2 mongo db and I get the following behavior : Mongo-connector stops after performing the init dump collection synchronization.
  
Here the stack :

- python 2.7
- mongo-connector==2.4
- pymongo==3.4.0
- urllib3==1.20
- Mongodb 3.4 
- OS : ubuntu 16.04 

the mongo-connector instanciation:
`mongo-connector -m mongosrouce:27017 -t mongocible:37017 -d mongo_doc_manager
`
and the associated log :

`2017-01-26 10:05:29,263 [ERROR] mongo_connector.util:92 - Fatal Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 90, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 199, in run
    cursor, cursor_empty = self.init_cursor()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 702, in init_cursor
    self.checkpoint = self.rollback()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 843, in rollback
    bson_obj_id_list = [obj_id(doc['_id']) for doc in doc_list]
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 209, in __validate
    "not %s" % (text_type.__name__, type(oid)))
TypeError: id must be an instance of (bytes, unicode, ObjectId), not <type 'int'>
2017-01-26 10:05:29,635 [ERROR] mongo_connector.connector:304 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 139845225649920)> unexpectedly stopped! Shutting down
`
Statistics on database shows that almost everything was synchronized:

Source : 
`Source

{
	"db" : "mydb",
	"collections" : 8,
	"views" : 0,
	"objects" : 877791,
	"avgObjSize" : 1386.7995274501561,
	"dataSize" : 1188789.203125,
	"storageSize" : 1502156,
	"numExtents" : 63,
	"indexes" : 18,
	"indexSize" : 68426.09375,
	"fileSize" : 2031616,
	"nsSizeMB" : 16,
	"extentFreeList" : {
		"num" : 0,
		"totalSize" : 0
	},
	"dataFileVersion" : {
		"major" : 4,
		"minor" : 22
	},
	"ok" : 1
}

Cible

{
	"db" : "mydb",
	"collections" : 8,
	"views" : 0,
	"objects" : **877767**,
	
}
`
Target:

`{
	"db" : "myDB",
	"collections" : 8,
	"views" : 0,
	"objects" : **877767**,
}` 

I wonder what happened. Could the problem come from a specific document ?

**Comment by ShaneHarvey** [comment]
The problem is that mongo-connector does not handle rollbacks properly when the '_id' field is not an ObjectId. That's why you see `TypeError: id must be an instance of (bytes, unicode, ObjectId), not <type 'int'>`. Unfortunately, there's no current work-around other than removing all documents that don't use ObjectId for '_id' which may not be possible for you.

You can read more and vote for the existing issue https://github.com/mongodb-labs/mongo-connector/issues/443. I think I have a simple idea for how to fix this issue for most use cases. I'll post a comment on the existing issue.
