### ISSUE TITLE
doesn't work with view ( createView mongo >= 3.4 )

### ISSUE THREAD

**Issue by robyinno** [mongodb-labs/mongo-connector#635]
in the namespaces with <db><view name> doesn't work
any roadmap to implement views ?

**Comment by robyinno** [comment]
In fact as in the oplog there is no view transaction of views its not possible to implement :D

**Comment by ShaneHarvey** [comment]
As you noted [MongoDB 3.4 views](https://docs.mongodb.com/manual/core/views/#reference-views) don't have any log of changes because they are read-only (non-materialized). mongo-connector cannot replicate changes to these views because those changes don't exist in the oplog.
