### ISSUE TITLE
Unique identifier for each oplog operation

### ISSUE THREAD

**Issue by erickhun** [mongodb-labs/mongo-connector#636]
Hi,
We're sending the oplog to a kafka stream that will be sanitized then sent .
We'd like to identify each oplog operation to be sure to not have duplicates of the operations. (we'd like to reprocess the stream if needed)

Here what give the oplog in the shell
```
> db.oplog.rs.find()
{
  "ts" : Timestamp(1395663575, 1),
  "h" : NumberLong("-5872498803080442915"),
  "v" : 2,
  "op" : "i",
  "ns" : "wiktory.items",
  "o" : {
    "_id" : ObjectId("533022d70d7e2c31d4490d22"),
    "author" : "JRR Hartley",
    "title" : "Flyfishing"
    }
}
```
It seems like this the unique identifier is the `"h"` field. I was wondering if it exists a way to get this value? Maybe I miss something in the options?

Thank you!

**Comment by ShaneHarvey** [comment]
Mongo-connector does not replicate the "h" field but the "ts" field is also unique and is sent to the DocManagers. If you're writing your own DocManager implementation the "ts" field is given as the `timestamp` argument. See https://github.com/mongodb-labs/mongo-connector/wiki/Writing-Your-Own-DocManager. 

Does this answer your question?

**Comment by erickhun** [comment]
It does! thank you @sha1sum  :)
