### ISSUE TITLE
how to  filter array feilds with includeFields?

### ISSUE THREAD

**Issue by yanpeipan** [mongodb-labs/mongo-connector#645]
```
{
  "list" : [
    {"name": "a", ...}
    {"name": "b", ...}
    {"name": "c", ...}
  ]
}
```

` "includeFields": [ "list.name", "list.0.name", "list.$.name", "list.*.name", "list.nested.name"]` not work

**Comment by ShaneHarvey** [comment]
mongo-connector does not support filtering fields inside arrays, you can only include or exclude the entire array field.

I added a note in the [filtering documentation](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#filtering-documents-per-namespace) about this.

**Comment by yanpeipan** [comment]
`PUT /xx/oo/_mapping`
```
"_source": {
    "includes": [
      "list.name"
      ]
  },
"properties": {
  "filelist": {
      "dynamic": false,
      "properties": {
        "name": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_max_word"
        }
      }
    }
}
```
it works to me

**Comment by ShaneHarvey** [comment]
Your example further shows that mongo-connector does support filtering insides arrays; the array field in MongoDB was improperly converted into an Elasticsearch object. If mongo-connector supported this kind of filtering, the array field would still be an array in Elasticsearch.
