### ISSUE TITLE
feature to map each mongo collection to different index in elasticsearch

### ISSUE THREAD

**Issue by sagargit2** [mongodb-labs/mongo-connector#663]
I am using `mongo-connector` to integrate `elasticsearch 5.0` with `mongodb 3.2`. Currently, `mongo-connector` [gives each MongoDB database its own index in Elasticsearch and each MongoDB collection becomes its own mapping type](https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch#elasticsearch-indexes-mappings-and-types) . But, I want to map each `mongo-collection` to different `index` in elasticsearch.

**Comment by ShaneHarvey** [comment]
See https://github.com/mongodb-labs/mongo-connector/issues/650.
