### ISSUE TITLE
Bi-directional setup question

### ISSUE THREAD

**Issue by eroji** [mongodb-labs/mongo-connector#667]
I read your documentation and wiki but could not find a clear answer on this. My question is, is it possible/safe to configure a bi-directional setup with mongo-connector so that I have 2 replicaset located at 2 different datacenters, so that both master nodes of each replicaset is able to accept writes and replicate that data over to the opposite side?

**Comment by ShaneHarvey** [comment]
It is not possible or safe to setup mongo-connector bi-directionally. mongo-connector only supports one-way data syncing.
