### ISSUE TITLE
Question: How to add a default field and with its default value to all records of index_type

### ISSUE THREAD

**Issue by sagargit2** [mongodb-labs/mongo-connector#674]
I want to attach a `default_field` with `default value` to every record within an `index_type`. 
**For eg:** `{"default_field" -> "default_value"}`
This `default_field` does not exist in `mongo-collection` but I need that field inside `elasticsearch` after mapping is done by `mongo-connector`. 
Is this something I could achieve with **mongo-connector**'s [Configuration](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options) ?

 **Note**: _I would like to add different (default_field,default_value) to different index_types._

**Comment by ShaneHarvey** [comment]
It's not possible to do this with mongo-connector's configuration but you can use [Elasticsearch's ingest node preprocessing](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) See: https://www.elastic.co/guide/en/elasticsearch/reference/master/set-processor.html
