### ISSUE TITLE
maintaining separate ES index for separate Mongo collections

### ISSUE THREAD

**Issue by yog989** [mongodb-labs/mongo-connector#680]
I am trying to sync 4 collections to separate indexes in ES
Using this command 

`mongo-connector -m localhost:27017 -t 1xx.xxx.xxx.xxx:9200 -o /opt/mongo-connector.oplog --auto-commit-interval=0 -d elastic2_doc_manager -n dbname.first,dbname.second,dbname.third,dbname.fourth`

But it is creating only one index name `dbname`, and putting data of all 4 collections i.e. `first, second, third, fourth` in the same index.
I want them to be in separate index. Any idea, how to achieve this.

**Comment by ShaneHarvey** [comment]
See https://github.com/mongodb-labs/mongo-connector/issues/650.
