### ISSUE TITLE
Oplog System Operations

### ISSUE THREAD

**Issue by ybeauchamps** [mongodb-labs/mongo-connector#689]
It can't find any specific references in the wiki but I'm assuming the connector ignores system operations in the oplog.  For example in a sharded cluster where documents might be moved from one shard to another.  I'm just looking for confirmation since I don't see a configuration option for filtering oplog documents.

Thanks,

**Comment by ShaneHarvey** [comment]
Yes, mongo-connector ignores system operations such as document migrations, see https://github.com/mongodb-labs/mongo-connector/issues/319

**Comment by ybeauchamps** [comment]
Perfect! Exactly what I was looking for.  

Thanks,
