### ISSUE TITLE
Apply deletions of a TTL-index

### ISSUE THREAD

**Issue by BlueRayONE** [mongodb-labs/mongo-connector#693]
I'm using a TTL (time to live) index to delete old entries in my collections. I noticed, that these deletions are not applied to my ElasticSearch instance by the connector, because these index-changes [do not appear in the oplog](http://stackoverflow.com/a/17652482).
There is no other nice way to apply the deletions anyway with the connector, right? 

(This issue could be a good hint in the issue-archive for people who are handling the same question and take a look here in the repo, like me before. Perhaps it could be also added to the wiki.)

**Comment by ShaneHarvey** [comment]
TTL index deletions *are* logged in the oplog by the primary and replicated via the oplog to secondaries, see https://docs.mongodb.com/manual/core/index-ttl/#replica-sets. The StackOverflow post you linked asks how to create a TTL index on the oplog itself which is not possible.

It is strange that you are not seeing deletions from TTL indexes though. Can you reproduce it? As far as I can tell TTL deletions show up as vanilla delete oplog entries:

```
rs:PRIMARY> db.eventlog.insert({})
WriteResult({ "nInserted" : 1 })
rs:PRIMARY> db.eventlog.createIndex( { "lastModifiedDate": 1 }, { expireAfterSeconds: 10})
{
	"createdCollectionAutomatically" : false,
	"numIndexesBefore" : 1,
	"numIndexesAfter" : 2,
	"ok" : 1
}
rs:PRIMARY> db.eventlog.find()
{ "_id" : ObjectId("58e67d265c88f2e5c14730c1") }
rs:PRIMARY> db.eventlog.insert({lastModifiedDate: ISODate()})
WriteResult({ "nInserted" : 1 })
rs:PRIMARY> db.eventlog.find()
{ "_id" : ObjectId("58e67d265c88f2e5c14730c1") }
{ "_id" : ObjectId("58e67de55c88f2e5c14730c4"), "lastModifiedDate" : ISODate("2017-04-06T17:41:57.551Z") }
rs:PRIMARY> // Wait a minute for the TTL deleter thread to run...
rs:PRIMARY> db.eventlog.find()
{ "_id" : ObjectId("58e67d265c88f2e5c14730c1") }
rs:PRIMARY> db.getSiblingDB('local').oplog.rs.find().sort({"$natural":-1}).skip(0).limit(2)
{ "ts" : Timestamp(1491500557, 1), "t" : NumberLong(1), "h" : NumberLong("1242841497882679314"), "v" : 2, "op" : "d", "ns" : "test.eventlog", "o" : { "_id" : ObjectId("58e67de55c88f2e5c14730c4") } }
{ "ts" : Timestamp(1491500517, 1), "t" : NumberLong(1), "h" : NumberLong("439027754211123178"), "v" : 2, "op" : "i", "ns" : "test.eventlog", "o" : { "_id" : ObjectId("58e67de55c88f2e5c14730c4"), "lastModifiedDate" : ISODate("2017-04-06T17:41:57.551Z") } }

**Comment by BlueRayONE** [comment]
Oh, my fault, read to fast and missunderstood it, sorry.

Yeah, then its really strange and I don't understand it, too. I tried to reproduce it and executed your example with an additional eye on the behaviour of ElasticSearch. The deletion "via TTL" was synced, too. 

In my running instance, I have a huge difference between ES and mongoDB: ES has 8 million documents more. I checked on a sample basis for documents which are older than the ``expireAfterSeconds``-value and found a lot, so it was my first idea that the TTL-deleted documents aren't synced. But with the proofed reproduction now I have absolutly no idea how this could happen.
I also hadn't a huge deletion with a "Last entry no longer in oplog cannot recover!"-error. 
(Of course, I need to do a full re-sync to get this fixed.)

Any other idea how this could happen? Can I provide further informations that could help? I'm using mongo-connector version 2.5.0, pymongo version 3.4.0, MongoDB version 3.2.10 and elastic2_doc_manager version 0.3.0.

**Comment by ShaneHarvey** [comment]
Could it be mongo-connector is lagging far behind the source cluster?

**Comment by BlueRayONE** [comment]
Yes, with 8 million documents. But there was no "Last entry no longer in oplog cannot recover!"-error, also no "gap" where I deleted the oplog-timestamp. So the reason is very unclear, especially because it has to do something with the TTL-index (all documents in ES which are "too much" are deleted by the TTL in mongoDB). 
I think I won't find the real reason and just do a resync. Will keep an eye on it, if it happens again...
