### ISSUE TITLE
The targ

### ISSUE THREAD

**Issue by pagepan** [mongodb-labs/mongo-connector#697]

**Comment by pagepan** [comment]
The target database also has a password, how to set the target database password？

**Comment by ShaneHarvey** [comment]
You should use a config file and pass the target authentication information in a MongoDB [connection string](https://docs.mongodb.com/manual/reference/connection-string/):

```js
{  
   "docManagers": [
        {
            "docManager": "mongo_doc_manager",
            "targetURL": "mongodb://user:password@localhost:27020",
        }
    ]
}
```

See https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Authentication#authentication-on-the-target-system.
