### ISSUE TITLE
Home page of wiki has broken links

### ISSUE THREAD

**Issue by akarsh** [mongodb-labs/mongo-connector#713]
Hi mongo-connector team,

I noticed the wiki home page has broken links.
https://github.com/mongodb-labs/mongo-connector/wiki

I assume it is a markdown issue.

It will be nice, if you can fix it.

Thank you

**Comment by ShaneHarvey** [comment]
Thanks for bringing this to our attention. It looks like Github changed their markdown link formatting from `[Page Title](Page Title)` to `[Page Title](Page-Title)`. Fixed!

**Comment by akarsh** [comment]
you are welcome
