### ISSUE TITLE
Bulk Load Failed

### ISSUE THREAD

**Issue by ybeauchamps** [mongodb-labs/mongo-connector#742]
Recently I've been having some errors come up.  No changes have been made to the environment and I had no issues with the connector.

`Yesterday 1:23:23 AM mongo-connector-prod-1 05 [ERROR] 23:23,084 [ERROR] mongo_connector.doc_managers.elastic2_doc_manager:491 - Bulk request failed with exception#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request#012    six.raise_from(e, None)#012  File "<string>", line 2, in raise_from#012  File "/usr/local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 382, in _make_request#012 `

At the moment I'm not sure the best method to troubleshoot the issue.  I'm assuming if the request to load to ES failed it will retry?

**Comment by makhdumi** [comment]
Unfortunately it looks like elastic2_doc_manager doesn't at all log the exception. See [here](https://github.com/mongodb-labs/elastic2-doc-manager/blob/683cc482e53a125b6115ff44aba18dd6031b5408/mongo_connector/doc_managers/elastic2_doc_manager.py#L491
).

What I've done is just add my own print or log statement to show the exception.

From what I can tell without doing any testing or running, it should retry. The connector uses [streaming_bulk](http://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.streaming_bulk) with `raise_on_error` set to the default `True`, and the bulk buffer is only cleared on a successful bulk upsert. But I would really confirm this yourself by adding some extra debug logging (e.g. maybe temporarily log the document IDs in the bulk buffer).

I've seen bulk failures from ES when the bulk request size (so I'd reduce the batch size) was too large or we had some malformed data inserted in MongoDB. i.e. you really need to know the exception to debug this.

I'd put in a Pull Request to log the actual exception. This repo doesn't seem to be maintained or supported anymore though D:. Apparently MongoDB favours Atlas and their proprietary/private `mongomirror` tool.

**Comment by ybeauchamps** [comment]
Thanks for the input, I'll see if I can get someone from the dev team to make those changes.
