### ISSUE TITLE
Stream from clustered MongoDB in Cloud

### ISSUE THREAD

**Issue by GitWebzer** [mongodb-labs/mongo-connector#748]
We try to stream data from Mongo in OpenShift cloud environment.
Our Mongo is a cluster with 3 shards, every shard is a 3-members replica set. Each of this members is a OpenShift pod.
As a mongo-connector 'mainAddress' we provide hosts of all of these members. But connector starts streaming data from one replica set only. So not all scope of data is transferred.
Is it possible to stream all data from such cluster configuration by using single connector, or we should manually starts several connector instances - for every replica set?

**Comment by ShaneHarvey** [comment]
In a sharded cluster, [mainaddress](https://github.com/mongodb-labs/mongo-connector/wiki/Configuration-Options#mainaddress) should point to the mongoses not all of the shards, eg:
```
"mainAddress": "mongodb://mongos-host1.example.net:27017,mongos-host2.example.net:27017/"
```

mongo-connector uses the mongos to discovers the shards and then connects directly to each shard to start syncing data. See https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#why-cant-i-use-mongo-connector-with-only-the-mongos

**Comment by GitWebzer** [comment]
We have one mongos. "Host" of every shard consists of addresses of 3 pods - 3 replica members.
sh.status():
```
shards:
	{  "_id" : "datars1",  "host" : "datars1/<host-of-rs1-pod1>:27017,<host-of-rs1-pod2>:27017,<host-of-rs1-pod3>:27017",  "state" : 1 }
	{  "_id" : "datars2",  "host" : "datars2/<host-of-rs2-pod1>:27017,<host-of-rs2-pod2>:27017,<host-of-rs2-pod3>:27017",  "state" : 1 }
	{  "_id" : "datars3",  "host" : "datars3/<host-of-rs3-pod1>:27017,<host-of-rs3-pod2>:27017,<host-of-rs3-pod3>:27017",  "state" : 1 }
```

I'm able to execute sh.status() under manual connection to `mongodb://<user>:<pass>@<host-of-mongos>/admin` (part of output is above), but if I provide this connection string to mongo-connector, I get "OperationFailure: not authorized on local to execute command { find: "oplog.rs", filter: {}, limit: 1, singleBatch: true }"

**Comment by GitWebzer** [comment]
We will grant our user to read from local database.

**Comment by ShaneHarvey** [comment]
If you want to sync all collections the simplest way is to give the mongo-connector user the `backup` role. This role gives mongo-connector all the privileges it needs: https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Authentication#required-permissions

Note the user needs to be created on the mongos and on each individual shard. This is so mongo-connector can authenticate to the mongos and directly to the replica sets.

**Comment by GitWebzer** [comment]
Thanks.
